/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.manager;

import duan1.DAO.ipml.dangkitangcaimpl;
import duan1.entity.dangkitangca;
import duan1.util.XAuth;
import duan1.util.XDialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class dangkitangcaManager extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dangkitangcaManager.class.getName());
    private List<dangkitangca> list = new ArrayList();
            private dangkitangcaimpl dao = new dangkitangcaimpl();
   
    /**
     * Creates new form dangkitangcaManager
     */
    public dangkitangcaManager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init(){
        filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Đăng Kí Tăng Ca");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã tăng ca", "Mã nv", "Ngày", "Checkin", "Checkout", "Số giờ", "Loại tăng ca", "Ghi chú", "Trạng thái", "Người Tạo"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
     int row = tb1.getSelectedRow();
if (row >= 0) {
    try {
        // Lấy mã tăng ca từ bảng
        String maTangCa = tb1.getValueAt(row, 0).toString();

        // Tìm entity từ database
        dangkitangca entity = dao.findById(maTangCa);

        if (entity != null) {
            // Mở form chỉnh sửa
            dangkitangca1manager editForm = new dangkitangca1manager((java.awt.Frame) this.getOwner(), true);
            editForm.setForm(entity);
            editForm.setVisible(true);

            // Refresh table sau khi chỉnh sửa
            filltable();
        } else {
            XDialog.alert("Không tìm thấy dữ liệu tăng ca!");
        }
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Lỗi khi mở form chỉnh sửa: " + e.getMessage());
    }
}

        
    }//GEN-LAST:event_tb1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dangkitangca1manager a = new dangkitangca1manager((java.awt.Frame)this.getOwner(), true);
        a.openForAddMode();
        a.setVisible(true);
        filltable(); // Refresh table after adding new record
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               dangkitangcaManager dialog = new dangkitangcaManager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

public void filltable() {
    DefaultTableModel model = (DefaultTableModel) tb1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    String id = XAuth.user.getMaNV();

    try {
        List<dangkitangca> list = dao.fillall1(String.valueOf(id)); // Lấy danh sách tăng ca theo mã nhân viên

        for (dangkitangca t : list) {
            Object[] row = new Object[]{
                t.getMaTangCa(),
                t.getMaNV(),
                t.getNgay(),
                t.getCheckin(),
                t.getCheckout(),
                t.getSoGio(),
                t.getLoaiTangCa(),
                t.getGhiChu(),
                t.getTrangThai(),
                t.getNguoiTao()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert(null, "Lỗi khi tải dữ liệu tăng ca: " + e.getMessage());
    }
}


}


