/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.manager;

import duan1.DAO.ipml.TTCaNhanDAOimpl;
import duan1.entity.ThongTin;
import duan1.util.XAuth;
import duan1.util.XDialog;

/**
 *
 * @author hang
 */
public class xemthongtincanhan extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(xemthongtincanhan.class.getName());

    /**
     * Creates new form xemthongtincanhan
     */
    public xemthongtincanhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init(){
    setfrom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnguoitao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_anh = new javax.swing.JLabel();
        txtgioitinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtngayvao = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtchucvu = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JLabel();
        rbotrangthai = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttrinhdo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtten = new javax.swing.JLabel();
        txtchuyennghanh = new javax.swing.JLabel();
        txtmaphong = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Cá Nhân");

        txtnguoitao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnguoitao.setText("jLabel37");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Ảnh");

        txtmanv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmanv.setText("jLabel3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Giới Tính");

        lb_anh.setText("jLabel5");

        txtgioitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtgioitinh.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Ngày Sinh");

        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaysinh.setText("jLabel17");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Địa Chỉ");

        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdiachi.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Ngày Vào Làm");

        txtngayvao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngayvao.setText("jLabel23");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Mã Chức Vụ");

        txtchucvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchucvu.setText("jLabel25");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("CCCD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Trạng Thái");

        txtcccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcccd.setText("jLabel27");

        rbotrangthai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbotrangthai.setText("jLabel5");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Trinh Do");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên");

        txttrinhdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttrinhdo.setText("jLabel29");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã Phòng");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Chuyên Nghành");

        txtten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtten.setText("jLabel8");

        txtchuyennghanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchuyennghanh.setText("jLabel31");

        txtmaphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaphong.setText("jLabel9");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Ngày Tạo");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Email");

        txtngaytao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaytao.setText("jLabel35");

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtemail.setText("jLabel11");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Người Tạo");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("SDT");

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbotrangthai))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaphong)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtmanv))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtten)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail)
                                            .addComponent(jLabel10))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsdt)
                                            .addComponent(jLabel12))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(txtgioitinh)))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtngaysinh)
                                            .addComponent(jLabel16)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtchucvu)
                                            .addComponent(jLabel24))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(txtcccd))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(txttrinhdo))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(txtchuyennghanh))))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(txtngaytao))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnguoitao)
                                            .addComponent(jLabel36)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(txtdiachi))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(txtngayvao))))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(29, 29, 29)
                        .addComponent(txtngaytao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel10)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmanv)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtten)
                                        .addComponent(txtemail))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel16)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtgioitinh)
                                    .addComponent(txtngaysinh)
                                    .addComponent(txtdiachi)
                                    .addComponent(txtngayvao)
                                    .addComponent(txtsdt))))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(29, 29, 29)
                                .addComponent(txtnguoitao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmaphong)
                                    .addComponent(rbotrangthai, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtchucvu)
                                    .addComponent(txtcccd)
                                    .addComponent(txttrinhdo)
                                    .addComponent(txtchuyennghanh))))))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                xemthongtincanhan dialog = new xemthongtincanhan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel rbotrangthai;
    private javax.swing.JLabel txtcccd;
    private javax.swing.JLabel txtchucvu;
    private javax.swing.JLabel txtchuyennghanh;
    private javax.swing.JLabel txtdiachi;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtgioitinh;
    private javax.swing.JLabel txtmanv;
    private javax.swing.JLabel txtmaphong;
    private javax.swing.JLabel txtngaysinh;
    private javax.swing.JLabel txtngaytao;
    private javax.swing.JLabel txtngayvao;
    private javax.swing.JLabel txtnguoitao;
    private javax.swing.JLabel txtsdt;
    private javax.swing.JLabel txtten;
    private javax.swing.JLabel txttrinhdo;
    // End of variables declaration//GEN-END:variables

    public void setfrom() {
        TTCaNhanDAOimpl a = new TTCaNhanDAOimpl();
        String Manv = XAuth.user.getMaNV();
        ThongTin tt = a.findById(Manv);
      
if (tt != null) {
    System.out.println("Tìm thấy nhân viên: " + tt.getHoTen());
} else {
    System.out.println("Không tìm thấy nhân viên.");
}


        if (tt != null) {
            txtmanv.setText(String.valueOf(tt.getMaNV()));
            txtten.setText(ensureNotNull(tt.getHoTen()));
            txtemail.setText(ensureNotNull(tt.getEmail()));
            txtsdt.setText(ensureNotNull(tt.getSDT()));
            txtgioitinh.setText(ensureNotNull(tt.getGioiTinh()));
            txtngaysinh.setText(tt.getNgaySinh() != null ? tt.getNgaySinh().toString() : "");
            txtdiachi.setText(ensureNotNull(tt.getDiaChi()));
            txtmaphong.setText(String.valueOf(tt.getMaPhong()));
            txtchucvu.setText(String.valueOf(tt.getMaChucVu()));
            txtcccd.setText(ensureNotNull(tt.getCCCD()));
            txttrinhdo.setText(ensureNotNull(tt.getTrinhDo()));
            txtchuyennghanh.setText(ensureNotNull(tt.getChuyenNganh()));
            txtngaytao.setText(tt.getNgayTao() != null ? tt.getNgayTao().toString() : "");
            txtnguoitao.setText(ensureNotNull(tt.getNguoiTao()));
            txtngayvao.setText(""); // Không có trong DB như bạn nói, có thể để trống
            rbotrangthai.setText(ensureNotNull(tt.getTrangThai()));

            // Nếu có ảnh, load vào JLabel (tuỳ bạn có dùng hay không)
            // if (tt.getPhoto() != null && !tt.getPhoto().isEmpty()) {
            //     lblPhoto.setIcon(new ImageIcon("duong_dan_anh/" + tt.getPhoto()));
            // }
        } else {
            XDialog.alert(null, "Không tìm thấy nhân viên.");
        }
    }

    private String ensureNotNull(String value) {
        return value == null ? "" : value;
    }

}
