/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.chamcongDAO;
import duan1.DAO.ipml.chamcongimpl;
import duan1.controller.Dashboardcontroller;
import duan1.entity.chamcong;
import duan1.util.XDialog;

import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author hang
 */
public class chamcongui extends javax.swing.JDialog implements Dashboardcontroller{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(chamcongui.class.getName());
    private chamcongDAO dao = new chamcongimpl();
    private Timer timer;

    /**
     * Creates new form chamcongui
     */
    public chamcongui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        initComponents();
        init();
        // Thêm WindowListener để xử lý sự kiện đóng cửa sổ
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    }

    public void init() {
        setLocationRelativeTo(null);
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        checkin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        checkout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Chấm công");

        lblTime.setText("Thời Gian");

        checkin.setText("checkin");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });

        jLabel3.setText("Vui lòng nhập mã nhân viên");

        checkout.setText("checkout");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\Quản-removebg-preview (7).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkin)
                                    .addGap(48, 48, 48)
                                    .addComponent(checkout)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblTime)
                        .addGap(30, 30, 30)
                        .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkin)
                            .addComponent(checkout)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        checkIn();
    }//GEN-LAST:event_checkinActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        checkOut();
    }//GEN-LAST:event_checkoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Hiển thị LoginJDialog
         openLoginDialog();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Phương thức cập nhật thông tin dashboard
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                chamcongui dialog = new chamcongui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkin;
    private javax.swing.JButton checkout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txt_manv;
    // End of variables declaration//GEN-END:variables

    private void showTime() {
        timer = new Timer(1000, e -> {
            lblTime.setText("Bây giờ: " + new java.sql.Time(System.currentTimeMillis()));
        });
        timer.start();
    }

  private void checkIn() {
    try {
        String maNV = txt_manv.getText();

        // Lấy ngày và giờ hiện tại
        LocalDate ngayLocal = LocalDate.now();
        LocalTime gioLocal = LocalTime.now();

        Date ngay = java.sql.Date.valueOf(ngayLocal);
        Time gioVao = Time.valueOf(gioLocal);

        chamcong cc = new chamcong();
        cc.setMaNV(maNV);
        cc.setNgay(ngay);
        cc.setCheckIn(gioVao);

        dao.checkIn(cc);

        String message = String.format("Check In thành công!\nNgày: %s\nGiờ vào: %s", ngayLocal, gioLocal.truncatedTo(ChronoUnit.SECONDS));
        XDialog.alert(message);
    } catch (Exception ex) {
      
    }
}


   private void checkOut() {
    try {
        String maNV = txt_manv.getText();
        LocalDate ngayLocal = LocalDate.now();
        Date ngay = java.sql.Date.valueOf(ngayLocal);
        Time gioRa = Time.valueOf(LocalTime.now());

        // Lấy giờ check-in từ DB
        Time gioVao = dao.getGioCheckIn(maNV, ngay);

        if (gioVao == null) {
            XDialog.alert("Không tìm thấy giờ check-in hôm nay!");
            return;
        }

        // Cập nhật giờ check-out
        dao.checkOut(maNV, ngay, gioRa);

        // Tính tổng thời gian làm việc
        long millisVao = gioVao.getTime();
        long millisRa = gioRa.getTime();
        long diffMillis = millisRa - millisVao;

        long diffHours = diffMillis / (1000 * 60 * 60);
        long diffMinutes = (diffMillis / (1000 * 60)) % 60;

        String message = String.format(
            "Check Out thành công!\nNgày: %s\nGiờ vào: %s\nGiờ ra: %s\nTổng thời gian làm: %d giờ %d phút",
            ngayLocal,
            gioVao.toLocalTime().truncatedTo(ChronoUnit.SECONDS),
            gioRa.toLocalTime().truncatedTo(ChronoUnit.SECONDS),
            diffHours,
            diffMinutes
        );

        XDialog.alert(message);
    } catch (Exception ex) {
        XDialog.alert("Lỗi check out: " + ex.getMessage());
    }
}



    
    private void openLoginDialog() {
        // Chỉ đóng form chấm công, không mở lại login1UI ở đây
        this.dispose();
    }
    
}




