/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duan1.UI;
import duan1.DAO.ipml.dashboardipml;
import duan1.controller.Dashboardcontroller;
import duan1.entity.dashboard;
import duan1.util.XAuth;
import duan1.util.XIcon;
import java.util.List;

/**
 *
 * @author hang
 */
public class dashboardUI extends javax.swing.JFrame implements Dashboardcontroller {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboardUI.class.getName());

    /**
     * Creates new form dashboardUI
     */
    public dashboardUI() {
        initComponents();
        setLocationRelativeTo(null);
       init1();
    }
    
    public void init1(){
    loadDashboard();
        setUserInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_nghiphep = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_TongNhanVien = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_chamcong = new javax.swing.JLabel();
        lb_vaitro = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1250, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1250, 10));

        jLabel2.setText("Vai TRò");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        jLabel3.setText("Tên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 30, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 241, 151));
        jLabel1.setText("Quản Lý Nhân Sự");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 270, 50));

        jButton1.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/add.png");
            if (iconUrl != null) {
                jButton1.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton1.setText("Quản Lý Tăng Ca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 160, 60));

        jButton2.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/absence (1).png");
            if (iconUrl != null) {
                jButton2.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton2.setText("Quản Lý Nghỉ Phép");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 170, 60));

        jButton3.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/key.png");
            if (iconUrl != null) {
                jButton3.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton3.setText("Quản Lý tài Khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 60));

        jButton4.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/wall-clock.png");
            if (iconUrl != null) {
                jButton4.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton4.setText("Quản Lý Chấm Công");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 170, 60));

        jButton6.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/user.png");
            if (iconUrl != null) {
                jButton6.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton6.setText("Quản Lý Nhân Viên");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jButton7.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/dollar.png");
            if (iconUrl != null) {
                jButton7.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton7.setText("Quản Lý Lương");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 150, 60));

        jButton8.setBackground(new java.awt.Color(57, 190, 189));
        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/contract.png");
            if (iconUrl != null) {
                jButton8.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, button will display without icon
        }
        jButton8.setText("Quản Lý Hợp Đồng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 160, 60));

        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/absence.png");
            if (iconUrl != null) {
                jLabel12.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, label will display without icon
        }
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 70, 60));

        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/users (1).png");
            if (iconUrl != null) {
                jLabel13.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, label will display without icon
        }
        jLabel13.setText("jLabel11");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, 80, 60));

        try {
            java.net.URL iconUrl = getClass().getResource("/duan1/icon/clock.png");
            if (iconUrl != null) {
                jLabel14.setIcon(new javax.swing.ImageIcon(iconUrl));
            }
        } catch (Exception e) {
            // Icon not found, label will display without icon
        }
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 70, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nghỉ Phép");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 30));

        lb_nghiphep.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_nghiphep.setText("jLabel11");
        jPanel1.add(lb_nghiphep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tổng Nhân Viên");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 140, 30));

        lb_TongNhanVien.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_TongNhanVien.setText("jLabel11");
        jPanel1.add(lb_TongNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Chấm Công");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 140, 30));

        lb_chamcong.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_chamcong.setText("jLabel11");
        jPanel1.add(lb_chamcong, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        lb_vaitro.setText("jLabel7");
        jPanel1.add(lb_vaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, -1));

        lb_name.setText("  ");
        jPanel1.add(lb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, -1));

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a3.setText("jLabel7");
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 270, 100));

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a2.setText("jLabel7");
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 270, 100));

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a1.setText("jLabel7");
        jPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 270, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\Quản-removebg-preview (4).png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 810, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("G:\\Downloads\\img\\1520222086640.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1260, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         this.showQuanlynhanvienJDialog(this);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.showQuanlychamcong(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.showquanlytaikhoan(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.showquanlynghiphep1UI(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.showTangCaUI(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.showQuanLyLuong1(this);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.showHopdongUI(this);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboardUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_TongNhanVien;
    private javax.swing.JLabel lb_chamcong;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_nghiphep;
    private javax.swing.JLabel lb_vaitro;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void loadDashboard() {
    dashboardipml dao = new dashboardipml();
    List<dashboard> list = dao.findAll();
    
    if (!list.isEmpty()) {
        dashboard dash = list.get(0); // Vì view chỉ trả về 1 dòng
        
        lb_TongNhanVien.setText(String.valueOf(dash.getTongNhanVien()));
        lb_chamcong.setText(String.valueOf(dash.getTongChamCongHomNay()));
        lb_nghiphep.setText(String.valueOf(dash.getTongNghiPhepHomNay()));
    }
}

    @Override
    public void init() {
         
    }

    private void setUserInfo() {
    if (XAuth.user != null) {
        lb_name.setText(XAuth.user.getFullname()); // hoặc getName(), tuỳ theo entity User
        if(XAuth.user.isVaiTro()){
            lb_vaitro.setText("Quản lý");
        }else{
             lb_vaitro.setText("Nhân viên");
        }
    } else {
        lb_name.setText("Chưa đăng nhập");
        lb_vaitro.setText("Không xác định");
    }
}
    
    
}


