/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import duan1.DAO.ipml.chucvuimpl;
import duan1.DAO.ipml.nhanvienimpl;
import duan1.DAO.ipml.phongbanipml;
import duan1.DAO.nhanvienDAO;
import duan1.controller.nhanviencontroller;
import duan1.entity.chucvu;
import java.awt.Color;
import duan1.entity.nhanvien;
import duan1.entity.phongban;
import duan1.util.XAuth;
import duan1.util.XDialog;
import duan1.util.XTable;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author hang
 */
public class quanlynhanvienui extends javax.swing.JDialog implements nhanviencontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlynhanvienui.class.getName());
    private List<nhanvien> nv = List.of();
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private nhanvienimpl repo = new nhanvienimpl();
    private nhanvienDAO dao = new nhanvienimpl();
    private boolean editMode = false;

    /**
     * Creates new form quanlynhanvien
     */
    public quanlynhanvienui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        init1();
    }

    public void init() {
        getContentPane().setBackground(new Color(240, 240, 240));
        
        // Style table đẹp hơn
        XTable.styleEmployeeTable(tb1);
        dateChooser1.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser1.hidePopup();
                }
            }
        });

        dateChooser1.setTextRefernce(txt_date);

    }

    public void init1() {
        defaultTableModel = (DefaultTableModel) tb1.getModel();
        fillTable();
        fillcbx();
        fillcbx1();
        setxt();

    }

    public void setxt() {
        String manv = XAuth.user.getMaNV();
        txt_manv.setText(manv);
        String ten = XAuth.user.getFullname();
        lb_nguoitao.setText(ten);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        btg = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_hoten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        txt_diachi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cccd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbx_trinhdo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_chuyennganh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bt_them = new javax.swing.JButton();
        txt_sua = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_nguoitao = new javax.swing.JLabel();
        cbx_phongban = new javax.swing.JComboBox<>();
        cbx_chucvu = new javax.swing.JComboBox<>();
        lb_anh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rd_danglamviec = new javax.swing.JRadioButton();
        rd_nghiviec = new javax.swing.JRadioButton();
        txt_manv = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        txt_timkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_timkiem = new javax.swing.JButton();
        bt_phongban = new javax.swing.JButton();
        bt_chucvu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });

        jLabel2.setText("Họ Và Tên");

        jLabel3.setText("Ngày Sinh");

        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        jLabel4.setText("Giới tính");

        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        jLabel5.setText("Số Điện Thoại");

        btg.add(rd_nam);
        rd_nam.setText("Nam");

        btg.add(rd_nu);
        rd_nu.setText("Nữ");
        rd_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_nuActionPerformed(evt);
            }
        });

        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });

        jLabel6.setText("Địa chỉ");

        txt_cccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cccdActionPerformed(evt);
            }
        });

        jLabel7.setText("Trình Độ");

        jLabel8.setText("CCCD");

        cbx_trinhdo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đại Học", "Cao Đẳng" }));

        jLabel9.setText("Chuyên ngành");

        txt_chuyennganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chuyennganhActionPerformed(evt);
            }
        });

        jLabel10.setText("Mã Nhân Viên");

        bt_them.setText("Thêm");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        txt_sua.setText("Sửa");
        txt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suaActionPerformed(evt);
            }
        });


        jLabel11.setText("Email");

        jLabel12.setText("Phòng ban");

        jLabel13.setText("Chức vụ");

        jLabel14.setText("Trạng Thái");

        jLabel16.setText("Người Tạo");

        lb_nguoitao.setText("abcdxyz");

        cbx_phongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_phongbanActionPerformed(evt);
            }
        });

        cbx_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_chucvuActionPerformed(evt);
            }
        });

        lb_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_anhMouseClicked(evt);
            }
        });

        jButton1.setText("Thêm ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rd_danglamviec);
        rd_danglamviec.setText("Đang làm việc");
        rd_danglamviec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_danglamviecActionPerformed(evt);
            }
        });

        buttonGroup2.add(rd_nghiviec);
        rd_nghiviec.setText("Nghỉ  Việc");

        txt_manv.setText("jLabel17");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(87, 87, 87)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt_date)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5))
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rd_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rd_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_trinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_nguoitao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbx_phongban, 0, 237, Short.MAX_VALUE)
                                .addComponent(cbx_chucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rd_danglamviec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(rd_nghiviec, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_them)
                        .addGap(77, 77, 77)
                        .addComponent(txt_sua)
                        .addGap(75, 75, 75)
))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_manv)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jButton5)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rd_nam)
                                    .addComponent(rd_nu))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_nguoitao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rd_danglamviec)
                                    .addComponent(rd_nghiviec))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel8)
                                .addGap(7, 7, 7)
                                .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(cbx_trinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_chuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_them)
                    .addComponent(txt_sua)
)
                .addGap(47, 47, 47))
        );

        tabs.addTab("Nhân Viên", jPanel1);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Ngày Sinh", "Giới tính", "Số điện thoại", "Địa chỉ", "CCCD", "Email", "Trình độ", "Chuyên ngành", "Ngày vào làm", "Người Tạo"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jLabel1.setText("Tìm Kiếm");

        bt_timkiem.setText("Tìm kiếm");
        bt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timkiemActionPerformed(evt);
            }
        });

        bt_phongban.setText("Phòng ban");
        bt_phongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_phongbanActionPerformed(evt);
            }
        });

        bt_chucvu.setText("Chức Vụ");
        bt_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_chucvuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bt_timkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(bt_phongban)
                .addGap(18, 18, 18)
                .addComponent(bt_chucvu)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_timkiem)
                    .addComponent(bt_phongban)
                    .addComponent(bt_chucvu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("Danh Sách", jPanel3);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("Quản lý nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser1.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
        SelectedDate d = dateChooser1.getSelectedDate();
        System.out.println(d.getDay() + "-" + d.getMonth() + "-" + d.getYear());
        System.out.println("Text : " + txt_date.getText());

    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void rd_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_nuActionPerformed

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void txt_cccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cccdActionPerformed

    private void txt_chuyennganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chuyennganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chuyennganhActionPerformed

    private void txt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suaActionPerformed
        // TODO add your handling code here:
        this.sua();
    }//GEN-LAST:event_txt_suaActionPerformed

    private void cbx_phongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_phongbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_phongbanActionPerformed

    private void cbx_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_chucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_chucvuActionPerformed

    private void lb_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_anhMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lb_anhMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.JFileChooser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:
        this.them();
    }//GEN-LAST:event_bt_themActionPerformed


    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tb1MouseClicked

    private void rd_danglamviecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_danglamviecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_danglamviecActionPerformed

    private void bt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_bt_timkiemActionPerformed

    private void bt_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_chucvuActionPerformed
        // TODO add your handling code here:
        chucvuui a = new chucvuui(null, true);
        a.setVisible(true);
    }//GEN-LAST:event_bt_chucvuActionPerformed

    private void bt_phongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_phongbanActionPerformed
        // TODO add your handling code here:
        Phongbanui a = new Phongbanui(null, true);
        a.setVisible(true);
    }//GEN-LAST:event_bt_phongbanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlynhanvienui dialog = new quanlynhanvienui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_chucvu;
    private javax.swing.JButton bt_phongban;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_timkiem;
    private javax.swing.ButtonGroup btg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<chucvu> cbx_chucvu;
    private javax.swing.JComboBox<phongban> cbx_phongban;
    private javax.swing.JComboBox<String> cbx_trinhdo;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel lb_nguoitao;
    private javax.swing.JRadioButton rd_danglamviec;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nghiviec;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_chuyennganh;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JLabel txt_manv;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JButton txt_sua;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    private boolean checkbox() {
        StringBuilder missing = new StringBuilder();

        if (txt_hoten.getText().trim().isEmpty()) {
            missing.append("- Họ Và Tên\n");
        }
        String ngaySinhStr = txt_date.getText().trim();
        if (ngaySinhStr.isEmpty()) {
            missing.append("- Ngày Sinh\n");
        }
        if (!rd_nam.isSelected() && !rd_nu.isSelected()) {
            missing.append("- Giới tính\n");
        }
        if (txt_sdt.getText().trim().isEmpty()) {
            missing.append("- Số Điện Thoại\n");
        }
        if (txt_diachi.getText().trim().isEmpty()) {
            missing.append("- Địa chỉ\n");
        }
        if (txt_cccd.getText().trim().isEmpty()) {
            missing.append("- CCCD\n");
        }
        if (txt_email.getText().trim().isEmpty()) {
            missing.append("- Email\n");
        }
        if (cbx_trinhdo.getSelectedItem() == null || String.valueOf(cbx_trinhdo.getSelectedItem()).trim().isEmpty()) {
            missing.append("- Trình Độ\n");
        }
        if (txt_chuyennganh.getText().trim().isEmpty()) {
            missing.append("- Chuyên ngành\n");
        }
        if (cbx_phongban.getSelectedItem() == null) {
            missing.append("- Phòng ban\n");
        }
        if (cbx_chucvu.getSelectedItem() == null) {
            missing.append("- Chức vụ\n");
        }
        if (!rd_danglamviec.isSelected() && !rd_nghiviec.isSelected()) {
            missing.append("- Trạng Thái\n");
        }

        // Nếu còn thiếu trường bắt buộc -> báo luôn
        if (missing.length() > 0) {
            XDialog.alert("Vui lòng nhập đầy đủ các ô sau:\n" + missing.toString());
            return false;
        }

        // Kiểm tra tuổi >= 18
        if (!isAtLeast18YearsOld(ngaySinhStr)) {
            XDialog.alert("Nhân viên phải từ 18 tuổi trở lên.");
            return false;
        }

        // Kiểm tra số điện thoại (10 số)
        if (!isValidPhoneNumber(txt_sdt.getText().trim())) {
            XDialog.alert("Số điện thoại phải có đúng 10 chữ số!");
            return false;
        }

        // Kiểm tra CCCD (12 số)
        if (!isValidCCCD(txt_cccd.getText().trim())) {
            XDialog.alert("CCCD phải có đúng 12 chữ số!");
            return false;
        }

        // Kiểm tra email
        if (!isValidEmail(txt_email.getText().trim())) {
            XDialog.alert("Email không đúng định dạng! Ví dụ: example@domain.com");
            return false;
        }

        return true;
    }

    private boolean isAtLeast18YearsOld(String dateText) {
        // Hỗ trợ vài định dạng phổ biến
        DateTimeFormatter[] fmts = new DateTimeFormatter[] {
            DateTimeFormatter.ofPattern("d-M-uuuu"),
            DateTimeFormatter.ofPattern("d/M/uuuu"),
            DateTimeFormatter.ofPattern("uuuu-M-d"),
            DateTimeFormatter.ofPattern("uuuu/M/d")
        };
        LocalDate birth = null;
        for (DateTimeFormatter f : fmts) {
            try {
                birth = LocalDate.parse(dateText, f);
                break;
            } catch (DateTimeParseException ignore) { }
        }
        if (birth == null) {
            // Thử parse theo DateChooser SelectedDate nếu người dùng nhấn Enter
            try {
                SelectedDate d = dateChooser1.getSelectedDate();
                if (d != null) {
                    birth = LocalDate.of(d.getYear(), d.getMonth(), d.getDay());
                }
            } catch (Exception ignore) { }
        }
        if (birth == null) {
            XDialog.alert("Định dạng ngày sinh không hợp lệ. Vui lòng nhập dạng dd-MM-yyyy hoặc dd/MM/yyyy.");
            return false;
        }
        LocalDate today = LocalDate.now();
        if (birth.isAfter(today)) {
            return false;
        }
        int years = Period.between(birth, today).getYears();
        return years >= 18;
    }

    /**
     * Kiểm tra số điện thoại có đúng 10 chữ số không
     */
    private boolean isValidPhoneNumber(String phoneNumber) {
        if (phoneNumber == null || phoneNumber.trim().isEmpty()) {
            return false;
        }
        // Loại bỏ khoảng trắng và ký tự đặc biệt
        String cleanPhone = phoneNumber.replaceAll("[\\s\\-\\(\\)]", "");
        // Kiểm tra có đúng 10 chữ số và bắt đầu bằng 0
        return cleanPhone.matches("^0\\d{9}$");
    }

    /**
     * Kiểm tra CCCD có đúng 12 chữ số không
     */
    private boolean isValidCCCD(String cccd) {
        if (cccd == null || cccd.trim().isEmpty()) {
            return false;
        }
        // Loại bỏ khoảng trắng và ký tự đặc biệt
        String cleanCCCD = cccd.replaceAll("[\\s\\-\\.]", "");
        // Kiểm tra có đúng 12 chữ số
        return cleanCCCD.matches("^\\d{12}$");
    }

    /**
     * Kiểm tra email có đúng định dạng không
     */
    private boolean isValidEmail(String email) {
        if (email == null || email.trim().isEmpty()) {
            return false;
        }
        // Regex pattern cho email
        String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        return email.trim().matches(emailPattern);
    }

    public nhanvien getForm() {
        try {
            nhanvien a = new nhanvien();

            if (!txt_manv.getText().trim().isEmpty()) {
                a.setMaNV(txt_manv.getText());
            }

            a.setHoTen(txt_hoten.getText().trim());
            a.setSdt(txt_sdt.getText().trim());
            a.setDiaChi(txt_diachi.getText().trim());
            a.setCccd(txt_cccd.getText().trim());
            a.setTrinhdo(String.valueOf(cbx_trinhdo.getSelectedItem()));
            a.setChuyennganh(txt_chuyennganh.getText().trim());
            a.setEmail(txt_email.getText().trim());

            a.setGioiTinh(rd_nam.isSelected() ? "Nam" : "Nữ");

            String ngaySinh = txt_date.getText().trim();
            if (ngaySinh.isEmpty()) {
                XDialog.alert("Vui lòng nhập ngày sinh.");
                return null;
            }
            a.setNgaySinh(ngaySinh);

            // Get actual department ID from selected phongban object
            phongban selectedPhongBan = (phongban) cbx_phongban.getSelectedItem();
            if (selectedPhongBan != null && selectedPhongBan.getMapb() != null) {
                a.setMaPhong(selectedPhongBan.getMapb());
            } else {
                XDialog.alert("Vui lòng chọn phòng ban!");
                return null;
            }

            // Get actual position ID from selected chucvu object  
            chucvu selectedChucVu = (chucvu) cbx_chucvu.getSelectedItem();
            if (selectedChucVu != null && selectedChucVu.getMacv() != null) {
                a.setMaChucVu(selectedChucVu.getMacv());
            } else {
                XDialog.alert("Vui lòng chọn chức vụ!");
                return null;
            }

            String trangThai = rd_danglamviec.isSelected() ? "Đang làm việc"
                    : rd_nghiviec.isSelected() ? "Nghỉ việc" : "Không xác định";
            a.setTrangThai(trangThai);

            a.setPhoto(lb_anh.getText());

            String nguoiTao = XAuth.user.getFullname(); // Giả sử có phương thức getHoTen()
            a.setNguoiTao(nguoiTao != null ? nguoiTao : lb_nguoitao.getText().trim());

            return a;

        } catch (Exception e) {
            XDialog.alert("Lỗi khi lấy dữ liệu từ form: " + e.getMessage());
            return null;
        }

    }

    public void setForm(nhanvien a) {
        fillcbx();
        fillcbx1();
        txt_manv.setText(String.valueOf(a.getMaNV()));
        txt_hoten.setText(a.getHoTen());
        txt_sdt.setText(a.getSdt());
        txt_diachi.setText(a.getDiaChi());
        txt_cccd.setText(a.getCccd());
        txt_chuyennganh.setText(a.getChuyennganh());
        txt_email.setText(a.getEmail());
        lb_nguoitao.setText(a.getNguoiTao());

        cbx_trinhdo.setSelectedItem(a.getTrinhdo());

        for (int i = 0; i < cbx_phongban.getItemCount(); i++) {
            phongban pb = (phongban) cbx_phongban.getItemAt(i);
            if (pb.getMapb().equals(a.getMaPhong())) {
                cbx_phongban.setSelectedIndex(i);
                break;
            }
        }

        // Set selected item cho cbx_chucvu
        for (int i = 0; i < cbx_chucvu.getItemCount(); i++) {
            chucvu cv = (chucvu) cbx_chucvu.getItemAt(i);
            if (cv.getMacv().equals(a.getMaChucVu())) {
                cbx_chucvu.setSelectedIndex(i);
                break;
            }
        }

        if ("Nam".equalsIgnoreCase(a.getGioiTinh())) {
            rd_nam.setSelected(true);
        } else {
            rd_nu.setSelected(true);
        }

        txt_date.setText(a.getNgaySinh());

        if ("Đang làm việc".equalsIgnoreCase(a.getTrangThai())) {
            rd_danglamviec.setSelected(true);
        } else if ("Nghỉ việc".equalsIgnoreCase(a.getTrangThai())) {
            rd_nghiviec.setSelected(true);
        }

        if (a.getPhoto() != null && !a.getPhoto().isEmpty()) {
            lb_anh.setIcon(new ImageIcon(a.getPhoto()));
            lb_anh.setText(a.getPhoto());
        } else {
            lb_anh.setIcon(null);
            lb_anh.setText("Chưa chọn ảnh");
        }
    }

    public void fillTable() {
        nv = dao.findAll();
        defaultTableModel.setRowCount(0);
        for (nhanvien list : nv) {
            defaultTableModel.addRow(new Object[]{
                list.getMaNV(),
                list.getHoTen(),
                list.getNgaySinh(),
                list.getGioiTinh(),
                list.getSdt(),
                list.getDiaChi(),
                list.getCccd(),
                list.getEmail(),
                list.getTrinhdo(),
                list.getChuyennganh(),
                list.getNgayVaoLam(),
                list.getNguoiTao(),
                list.getPhoto()
            });
        }
    }

    @Override
    public void them() {
        if (editMode) {
            XDialog.alert("Đang ở chế độ sửa, không thể thêm. Vui lòng bấm Clear để tạo mới.");
            return;
        }
        if (!checkbox()) {
            return;
        }
        nhanvien entity = getForm();
        if (entity == null) {
            return;
        }
        dao.create(entity);
        fillTable();
        clear();
        XDialog.alert("Thêm thành công!");
    }

    @Override
    public void sua() {
        if (!checkbox()) {
            return;
        }
        nhanvien entity = getForm();
        if (entity == null) {
            return;
        }
        try {
            dao.update(entity);
            fillTable();
            XDialog.alert("Cập nhật thành công!");
        } catch (Exception e) {
            XDialog.alert("Lỗi khi cập nhật: " + e.getMessage());
        }
    }

    @Override
    public void xoa() {
        // Chặn xoá nhân viên trực tiếp trên màn hình này
        XDialog.alert("Không thể xoá nhân viên trên màn hình này. Vui lòng chuyển trạng thái 'Nghỉ việc' thay vì xoá.");
        return;
    }

    @Override
    public void edit() {
        int viewRow = tb1.getSelectedRow();
        if (viewRow < 0) {
            XDialog.alert("Vui lòng chọn nhân viên!");
            return;
        }

        int modelRow = tb1.convertRowIndexToModel(viewRow);
        Object value = tb1.getModel().getValueAt(modelRow, 0);
        if (value == null) {
            XDialog.alert("Không lấy được mã nhân viên!");
            return;
        }

        String maNV = String.valueOf(value).trim();
        nhanvien entity = dao.findById(maNV);
        if (entity == null) {
            XDialog.alert("Không tìm thấy nhân viên!");
            return;
        }

        setForm(entity);
        tabs.setSelectedIndex(0);
        editMode = true;
        bt_them.setEnabled(false);
    }

    public void timkiem() {
        defaultTableModel.setRowCount(0);
        String keyword = txt_timkiem.getText().trim().toLowerCase();
        for (nhanvien list : nv) {
            if (list.getHoTen().toLowerCase().contains(keyword)) {
                defaultTableModel.addRow(new Object[]{
                    list.getMaNV(),
                    list.getHoTen(),
                    list.getNgaySinh(),
                    list.getGioiTinh(),
                    list.getSdt(),
                    list.getDiaChi(),
                    list.getCccd(),
                    list.getEmail(),
                    list.getTrinhdo(),
                    list.getChuyennganh(),
                    list.getNgayVaoLam(),
                    list.getNguoiTao(),
                    list.getPhoto()
                });
            }
        }
    }

    @Override
    public void JFileChooser() {
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String path = file.getAbsolutePath();
            lb_anh.setIcon(new ImageIcon(path));
            lb_anh.setText(path);
        }
    }

    @Override
    public void clear() {
        setForm(new nhanvien());
        txt_manv.setText("");
        rd_nam.setSelected(true);
        rd_danglamviec.setSelected(true);
        lb_anh.setText("Chưa chọn ảnh");
        lb_anh.setIcon(null);
        editMode = false;
        bt_them.setEnabled(true);
    }

    public void fillcbx() {
        phongbanipml dao = new phongbanipml();
        DefaultComboBoxModel<phongban> model = new DefaultComboBoxModel<>();
        for (phongban pb : dao.findall1()) {
            model.addElement(pb);
        }
        cbx_phongban.setModel(model);

    }

    public void fillcbx1() {
        chucvuimpl dao = new chucvuimpl();
        DefaultComboBoxModel<chucvu> model = new DefaultComboBoxModel<>();
        for (chucvu pb : dao.findall1()) {
            model.addElement(pb);
        }
        cbx_chucvu.setModel(model);

    }

}
