/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.ipml.quanlytaikhoanipml;
import duan1.controller.quanlychamcongcontroller;
import duan1.controller.quanlytaikhoancontroller;
import duan1.entity.quanlytaikhoan;
import duan1.entity.role;
import duan1.util.XTable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlytaikhoanUI extends javax.swing.JDialog implements quanlytaikhoancontroller{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlytaikhoanUI.class.getName());
    private quanlytaikhoanipml dao = new quanlytaikhoanipml(); 
      private List<quanlytaikhoan> nv = new ArrayList<>();
      private List<role> roles = new ArrayList<>();

    /**
     * Creates new form quanlytaikhoanUI
     */
    public quanlytaikhoanUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init(){
        // Style tables đẹp hơn
        XTable.styleTable(tb1);
        XTable.styleTable(tb2);
        
        fillTable();
        fillTable1();
        fillRoles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rd_hd = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rd_khd = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_phanquyen = new javax.swing.JComboBox<>();
        txt_manv = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup2.add(rd_hd);
        rd_hd.setText("Hoạt Động");
        rd_hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_hdActionPerformed(evt);
            }
        });

        jLabel4.setText("Passworld");

        jLabel6.setText("Mã Nhân Viên");

        jLabel1.setText("Username");

        jLabel2.setText("Trạng thái");

        jLabel3.setText("Phân quyền");

        buttonGroup2.add(rd_khd);
        rd_khd.setText("Không Hoạt Động");
        rd_khd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_khdActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ tên", "Tên Đăng Nhập", "Mật Khẩu", "Vai Trò", "Trạng Thái"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Tên Đăng Nhập", "Mật Khẩu", "Vai Trò", "Trạng Thái"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb2);

        jLabel5.setText("Tài Khoản");

        jLabel7.setText("Chưa có tài Khoản");

        jLabel8.setText("Họ tên");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Quản Lý Tài Khoản");

        cbx_phanquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_manv.setText("jLabel10");

        txt_hoten.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbx_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton2)
                                            .addComponent(rd_hd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_khd))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_manv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(89, 89, 89))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hoten)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_manv)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rd_hd)
                                    .addComponent(rd_khd))
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbx_phanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd_hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_hdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_hdActionPerformed

    private void rd_khdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_khdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_khdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.them();
        fillTable1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.sua();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        this.eidt();
    }//GEN-LAST:event_tb1MouseClicked

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        // TODO add your handling code here:
        this.eidt1();
    }//GEN-LAST:event_tb2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlytaikhoanUI dialog = new quanlytaikhoanUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbx_phanquyen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd_hd;
    private javax.swing.JRadioButton rd_khd;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JLabel txt_hoten;
    private javax.swing.JLabel txt_manv;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public quanlytaikhoan getform() {
        quanlytaikhoan a = new quanlytaikhoan();
        a.setTendangnhap(txt_username.getText());
        a.setMatkhau(txt_password.getText());
        a.setManv(txt_manv.getText());
        a.setTrangthai(rd_hd.isSelected());
        int selectedIndex = cbx_phanquyen.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < roles.size()) {
            role selectedRole = roles.get(selectedIndex);
            a.setRoleid(selectedRole.getRoleid());
            a.setRolename(selectedRole.getRolename());
            boolean isAdmin = selectedRole.getRolename() != null && selectedRole.getRolename().equalsIgnoreCase("Admin");
            a.setVaitro(isAdmin);
        } else {
            a.setRoleid(0);
            a.setRolename(null);
            a.setVaitro(false);
        }
        return a;
    }

    public void setform(quanlytaikhoan b) {
        txt_manv.setText(String.valueOf(b.getManv()));
        txt_username.setText(b.getTendangnhap());
        txt_password.setText(b.getMatkhau());
        txt_hoten.setText(b.getHoten());
        
        // Set selected role in combo box
        int selIndex = -1;
        if (roles != null && !roles.isEmpty()) {
            for (int i = 0; i < roles.size(); i++) {
                if (b.getRoleid() != 0 && roles.get(i).getRoleid() == b.getRoleid()) {
                    selIndex = i;
                    break;
                }
            }
            if (selIndex == -1 && b.getRolename() != null) {
                for (int i = 0; i < roles.size(); i++) {
                    if (b.getRolename().equalsIgnoreCase(roles.get(i).getRolename())) {
                        selIndex = i;
                        break;
                    }
                }
            }
        }
        if (selIndex >= 0) {
            cbx_phanquyen.setSelectedIndex(selIndex);
        } else if (cbx_phanquyen.getItemCount() > 0) {
            cbx_phanquyen.setSelectedIndex(0);
        }

        // Trạng thái
        if (b.isTrangthai()) {
            rd_hd.setSelected(true);     
            rd_khd.setSelected(false);
        } else {
            rd_hd.setSelected(false);
            rd_khd.setSelected(true);    
        }
    }
    
    public void fillTable() {
    DefaultTableModel model = (DefaultTableModel) tb1.getModel();
    model.setRowCount(0); // Xóa trắng bảng

    nv = dao.findAll(); // <-- cập nhật lại danh sách toàn cục
    for (quanlytaikhoan tk : nv) {
        String vaiTro = tk.getRolename() != null ? tk.getRolename() : "";
        String trangThai = tk.isTrangthai() ? "Hoạt động" : "Khóa";

        model.addRow(new Object[]{
            tk.getManv(),
            tk.getHoten(),
            tk.getTendangnhap(),
            tk.getMatkhau(),
            vaiTro,
            trangThai
        });
    }
}
    
    
     public void fillTable1() {
    DefaultTableModel model = (DefaultTableModel) tb2.getModel();
    model.setRowCount(0); // Xóa trắng bảng

    nv = dao.findall1(); // <-- cập nhật lại danh sách toàn cục
    for (quanlytaikhoan tk : nv) {
        String vaiTro = "";
        String trangThai = tk.isTrangthai() ? "Hoạt động" : "Chưa có tài khoản";

        model.addRow(new Object[]{
            tk.getManv(),
            tk.getHoten(),
            tk.getTendangnhap(),
            tk.getMatkhau(),
            vaiTro,
            trangThai
        });
    }
}

    private void fillRoles() {
        roles = dao.getAllRoles();
        cbx_phanquyen.removeAllItems();
        if (roles != null) {
            for (role r : roles) {
                cbx_phanquyen.addItem(r.getRolename());
            }
        }
    }

    @Override
    public void them() {
        try {
             if (!validateAccountForm()) {
            return;
        }
        quanlytaikhoan entity = this.getform();
        dao.create(entity);
        this.fillTable();
        } catch (Exception e) {
            System.out.println("lỗi");
        }
        
      
    }

    @Override
    public void sua() {
         if (!validateAccountForm()) {
            return;
        }
         quanlytaikhoan entity = this.getform();

        // Cảnh báo & giữ nguyên phân quyền nếu tài khoản hiện tại là Admin
        try {
            quanlytaikhoan current = dao.findById(entity.getTendangnhap());
            if (current != null && current.getRoleid() == 1 && entity.getRoleid() != current.getRoleid()) {
                JOptionPane.showMessageDialog(this, "Không thể sửa phân quyền nếu bạn là Admin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                // Đặt lại combobox về phân quyền hiện tại trong DB
                int selIndex = -1;
                for (int i = 0; i < roles.size(); i++) {
                    if (roles.get(i).getRoleid() == current.getRoleid()) {
                        selIndex = i;
                        break;
                    }
                }
                if (selIndex >= 0) {
                    cbx_phanquyen.setSelectedIndex(selIndex);
                    role r = roles.get(selIndex);
                    entity.setRoleid(r.getRoleid());
                    entity.setRolename(r.getRolename());
                }
            }
        } catch (Exception ex) {
            // Bỏ qua lỗi đọc DB, tiếp tục update theo logic DAO (DAO đã chặn đổi role Admin)
        }

        dao.update(entity);
         this.fillTable();
    }

    @Override
    public void eidt() {
       int index = tb1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Reload data for table 1 to ensure correct data
        List<quanlytaikhoan> table1Data = dao.findAll();
        if (index >= table1Data.size()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        quanlytaikhoan entity = table1Data.get(index);
        this.setform(entity);
    }
    
    public void eidt1() {
       int index = tb2.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để chỉnh sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Reload data for table 2 to ensure correct data
        List<quanlytaikhoan> table2Data = dao.findall1();
        if (index >= table2Data.size()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        quanlytaikhoan entity = table2Data.get(index);
        this.setform(entity);
    }

    private boolean validateAccountForm() {
        String username = txt_username.getText();
        String password = txt_password.getText();
        String maNV = txt_manv.getText();
        String hoTen = txt_hoten.getText();

        if (username == null || username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_username.requestFocus();
            return false;
        }
        
        // Kiểm tra tên đăng nhập không được chứa khoảng trắng
        if (username.contains(" ")) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được chứa khoảng trắng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_username.requestFocus();
            return false;
        }
        
        // Kiểm tra tên đăng nhập không được chứa ký tự tiếng Việt
        if (!username.matches("^[a-zA-Z0-9_]+$")) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập chỉ được chứa chữ cái tiếng Anh, số và dấu gạch dưới!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_username.requestFocus();
            return false;
        }
        
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_password.requestFocus();
            return false;
        }
        if (hoTen == null || hoTen.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_hoten.requestFocus();
            return false;
        }
        if (maNV == null || maNV.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txt_manv.requestFocus();
            return false;
        }
        if (cbx_phanquyen.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phân quyền!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            cbx_phanquyen.requestFocus();
            return false;
        }
        if (!rd_hd.isSelected() && !rd_khd.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái tài khoản!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
}
