/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duan1.UI;

import duan1.DAO.ipml.dashboardipml;
import duan1.controller.Dashboardcontroller;
import duan1.entity.dashboard;
import duan1.util.XAuth;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author hang
 */
public class dashboard1UI extends javax.swing.JFrame implements Dashboardcontroller{

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard1UI.class.getName());

    /**
     * Creates new form dashboard1UI
     */
    public dashboard1UI() {
        initComponents();
        init();
        setLocationRelativeTo(null);
    }
    
    public void init(){
     setLabelNhanVien();
    loadDashboard(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_nghiphep = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_luong = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_chamcong = new javax.swing.JLabel();
        lb_manv = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_vaitro = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1260, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1250, 10));

        jLabel2.setText("Mã nhân viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, -1));

        jLabel3.setText("Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\Quản-removebg-preview (3).png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 241, 151));
        jLabel1.setText("Quản Lý Nhân Sự");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 280, 50));

        jButton1.setBackground(new java.awt.Color(57, 190, 189));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/add.png"))); // NOI18N
        jButton1.setText("Đăng Kí Tăng ca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 160, 60));

        jButton3.setBackground(new java.awt.Color(57, 190, 189));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/key.png"))); // NOI18N
        jButton3.setText("Xem bảng lương");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 160, 60));

        jButton6.setBackground(new java.awt.Color(57, 190, 189));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/user.png"))); // NOI18N
        jButton6.setText("Xem thông tin cá nhân");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 60));

        jButton8.setBackground(new java.awt.Color(57, 190, 189));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/contract.png"))); // NOI18N
        jButton8.setText("Xem chấm công");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 160, 60));

        jButton2.setBackground(new java.awt.Color(57, 190, 189));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/add.png"))); // NOI18N
        jButton2.setText("Xin nghỉ phép");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 160, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/absence.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 70, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/users (1).png"))); // NOI18N
        jLabel13.setText("jLabel11");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 290, 80, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1/icon/clock.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 70, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nghỉ Phép");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 30));

        lb_nghiphep.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_nghiphep.setText("jLabel11");
        getContentPane().add(lb_nghiphep, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lương");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 140, 30));

        lb_luong.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_luong.setText("jLabel11");
        getContentPane().add(lb_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Chấm Công");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 140, 30));

        lb_chamcong.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lb_chamcong.setText("jLabel11");
        getContentPane().add(lb_chamcong, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        lb_manv.setText("jLabel7");
        getContentPane().add(lb_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        lb_name.setText("  ");
        getContentPane().add(lb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 190, -1));

        jLabel7.setText("Vai Trò");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, -1));

        lb_vaitro.setText("jLabel7");
        getContentPane().add(lb_vaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, -1));

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a3.setText("jLabel7");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 270, 100));

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a2.setText("jLabel7");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 270, 100));

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\istockphoto-1560643157-612x612.jpg")); // NOI18N
        a1.setText("jLabel7");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 270, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\Quản-removebg-preview (4).png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 810, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\img\\1520222086640.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 780));

        jLabel18.setText("jLabel11");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.showxemcanhan(this);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.showdangkitangca(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.showXemBangLuongNhanVien(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.showxemchamcongnhanvienmanager(this);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.showquanlynghiphepUI(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard1UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_chamcong;
    private javax.swing.JLabel lb_luong;
    private javax.swing.JLabel lb_manv;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_nghiphep;
    private javax.swing.JLabel lb_vaitro;
    // End of variables declaration//GEN-END:variables

private void loadDashboard() {
    dashboardipml dao = new dashboardipml();
    String manv = lb_manv.getText();
    List<dashboard> list = dao.findall1(manv);

    if (!list.isEmpty()) {
        dashboard dash = list.get(0); // Vì view chỉ trả về 1 dòng

        // ✅ Định dạng tiền tệ Việt Nam
        NumberFormat vndFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
        String tongLuongVND = vndFormat.format(dash.getTongluong());

        lb_luong.setText(tongLuongVND); // Hiển thị dạng "1.752.307 ₫"
        lb_chamcong.setText(String.valueOf(dash.getSoNgayDiLam()));
        lb_nghiphep.setText(String.valueOf(dash.getSoNgayNghiPhep()));
    }
}


    private void setLabelNhanVien() {
        // Giả sử XAuth.user là đối tượng User hiện tại
        if (XAuth.user != null) {
            lb_name.setText(XAuth.user.getFullname()); // hoặc getHoTen(), tuỳ thuộc vào class User
            lb_manv.setText(String.valueOf(XAuth.user.getMaNV()));
            if (XAuth.user.isVaiTro()) {
                lb_vaitro.setText("Quản lý");
            } else {
                lb_vaitro.setText("Nhân viên");
            }
        } else {
            lb_name.setText("Chưa đăng nhập");
            lb_vaitro.setText("Không xác định");
        }
    }
    
    
    
    

}
