/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.ipml.Hopdongipml;
import duan1.DAO.ipml.Loaihopdongipml;
import duan1.DAO.ipml.nhanvienimpl;
import duan1.controller.hopdongcontroller;
import duan1.entity.Hopdong;
import duan1.entity.Loaihopdong;
import duan1.util.XAuth;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import duan1.util.XDate;
import java.util.Calendar;
import java.util.Date;
import java.text.Normalizer;

/**
 *
 * @author hang
 */
public class HopdongUI extends javax.swing.JDialog implements hopdongcontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HopdongUI.class.getName());
    private Hopdongipml dao = new Hopdongipml();
    private Loaihopdongipml loaihdDao = new Loaihopdongipml();
    private nhanvienimpl nhanvienDao = new nhanvienimpl();
    private List<Hopdong> list = new ArrayList<>();
    private List<Loaihopdong> listLoaiHD = new ArrayList<>();
    private javax.swing.Timer tb2RefreshTimer;

    /**
     * Creates new form HopdongUI
     */
    public HopdongUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        fillTable();
        fillComboBox();
        setDefaultCreationInfo();
        fillTable1();

        // Tự động reload bảng tb2 định kỳ
        tb2RefreshTimer = new javax.swing.Timer(5000, evt -> fillTable1());
        tb2RefreshTimer.start();

        // Dừng timer khi đóng cửa sổ
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (tb2RefreshTimer != null) {
                    tb2RefreshTimer.stop();
                }
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (tb2RefreshTimer != null) {
                    tb2RefreshTimer.stop();
                }
            }
        });

        // Bỏ lọc mặc định theo combobox (đã loại bỏ chức năng lọc)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_mahd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_hoten = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ngaybatdau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_ngayketthuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_luongthoathuan = new javax.swing.JTextField();
        rd_conhieuluc = new javax.swing.JRadioButton();
        rd_hethieuluc = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_ngaytao = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_nguoitao = new javax.swing.JLabel();
        bt_xacnhan = new javax.swing.JButton();
        cbx_loaihopdong = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        bt_xacnhan1 = new javax.swing.JButton();
        bt_xacnhan2 = new javax.swing.JButton();
        txt_manv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        bt_timkiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Mã NV", "Họ Tên", "Loại Hợp Đồng", "Ngày bắt đầu", "Ngày kết thúc", "Lương thoả thuận", "Trạng thái", "Ngày tạo", "Người tạo"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nv", "Họ tên", "Phòng Ban", "Chức Vụ", "Trạng Thái HĐ"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb2);

        jLabel3.setText("Nhân Viên Chưa có Hợp Đồng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabs.addTab("Danh sách", jPanel1);

        jLabel2.setText("Mã hợp đồng");

        lb_mahd.setText("jLabel3");

        jLabel5.setText("Mã Nhân Viên");

        jLabel6.setText("Họ Tên");

        lb_hoten.setText("jLabel4");

        jLabel7.setText("Ngày Bắt Đầu");

        jLabel8.setText("Ngày Kết Thúc");

        jLabel9.setText("Lương Thoả Thuận");

        buttonGroup1.add(rd_conhieuluc);
        rd_conhieuluc.setText("Còn Hiệu Lực");

        buttonGroup1.add(rd_hethieuluc);
        rd_hethieuluc.setText("Hết Hiệu Lực");

        jLabel10.setText("Trạng Thái");

        jLabel11.setText("Ngày Tạo");

        lb_ngaytao.setText("jLabel12");

        jLabel13.setText("Người Tạo");

        lb_nguoitao.setText("jLabel12");

        bt_xacnhan.setText("Sửa");
        bt_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xacnhanActionPerformed(evt);
            }
        });

        cbx_loaihopdong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Loại Hợp Đồng");

        bt_xacnhan1.setText("Thêm");
        bt_xacnhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xacnhan1ActionPerformed(evt);
            }
        });

        bt_xacnhan2.setText("Xoá");
        bt_xacnhan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xacnhan2ActionPerformed(evt);
            }
        });

        txt_manv.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(lb_mahd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_loaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rd_conhieuluc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(rd_hethieuluc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(txt_luongthoathuan, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(463, 463, 463))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txt_ngayketthuc)
                            .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nguoitao, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(lb_ngaytao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_xacnhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(bt_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bt_xacnhan2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_ngaytao))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_nguoitao)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_luongthoathuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_mahd)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_manv)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_hoten)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rd_conhieuluc)
                            .addComponent(rd_hethieuluc)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cbx_loaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_xacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_xacnhan2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_xacnhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        tabs.addTab("Hợp đồng", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý hợp đồng");

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });

        bt_timkiem.setText("Tìm Kiếm");
        bt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(bt_timkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_timkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_xacnhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xacnhan1ActionPerformed
        // TODO add your handling code here:
        this.them();
    }//GEN-LAST:event_bt_xacnhan1ActionPerformed

    private void bt_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xacnhanActionPerformed
        // TODO add your handling code here:
        this.sua();
    }//GEN-LAST:event_bt_xacnhanActionPerformed

    private void bt_xacnhan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xacnhan2ActionPerformed
        // TODO add your handling code here:
        this.xoa();
    }//GEN-LAST:event_bt_xacnhan2ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tb1MouseClicked

    private void cbx_loaihopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_loaihopdongActionPerformed
        // TODO add your handling code here:
        calculateContractDates();
    }//GEN-LAST:event_cbx_loaihopdongActionPerformed


    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
        // TODO add your handling code here:
        edit1();
    }//GEN-LAST:event_tb2MouseClicked

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void bt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timkiemActionPerformed
        // TODO add your handling code here
        timkiem();
    }//GEN-LAST:event_bt_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                HopdongUI dialog = new HopdongUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_timkiem;
    private javax.swing.JButton bt_xacnhan;
    private javax.swing.JButton bt_xacnhan1;
    private javax.swing.JButton bt_xacnhan2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_loaihopdong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_hoten;
    private javax.swing.JLabel lb_mahd;
    private javax.swing.JLabel lb_ngaytao;
    private javax.swing.JLabel lb_nguoitao;
    private javax.swing.JRadioButton rd_conhieuluc;
    private javax.swing.JRadioButton rd_hethieuluc;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField txt_luongthoathuan;
    private javax.swing.JLabel txt_manv;
    private javax.swing.JTextField txt_ngaybatdau;
    private javax.swing.JTextField txt_ngayketthuc;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void them() {
        try {

            Hopdong entity = this.getform(false);

            if (entity == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: Không thể tạo hợp đồng!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (entity.getManv() == null || entity.getManv().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
                txt_manv.requestFocus();
                return;
            }

            // Kiểm tra nhân viên có tồn tại không và lấy họ tên
            String hoTenNhanVien = getHoTenNhanVien(entity.getManv());
            if (hoTenNhanVien == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Mã nhân viên không tồn tại!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
                txt_manv.requestFocus();
                return;
            }
            // Set họ tên vào entity (từ database)
            entity.setHoten(hoTenNhanVien);

            if (entity.getMaloaihd() == null || entity.getMaloaihd().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại hợp đồng!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
                cbx_loaihopdong.requestFocus();
                return;
            }

            // Set ngày tạo và người tạo
            Date currentDate = XDate.now();
            entity.setNgaytao(XDate.format(currentDate, "dd/MM/yyyy"));
            entity.setNguoitao(XAuth.user.getFullname());

            Hopdong result = dao.create(entity);
            if (result != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm hợp đồng thành công! Mã HD: " + result.getMahd(), "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.fillTable();
                this.fillTable1();
                this.clearForm();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: Không thể thêm hợp đồng!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void sua() {
        try {
            Hopdong entity = this.getform();
            if (entity != null && entity.getMahd() != null && !entity.getMahd().isEmpty()) {
                // Giữ nguyên ngày tạo và người tạo
                String ngayTao = lb_ngaytao.getText();
                String nguoiTao = lb_nguoitao.getText();
                if (ngayTao != null && !ngayTao.isEmpty()) {
                    entity.setNgaytao(ngayTao);
                }
                if (nguoiTao != null && !nguoiTao.isEmpty()) {
                    entity.setNguoitao(XAuth.user.getFullname());
                }

                dao.update(entity);
                this.fillTable();
                this.fillTable1();
                this.clearForm();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void xoa() {
        try {
            String id = lb_mahd.getText();
            if (id != null && !id.isEmpty()) {
                dao.deleteById(id);
                this.fillTable();
                this.fillTable1();
                this.clearForm();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Hopdong getform() {
        return getform(true); // Mặc định bao gồm mahd cho việc sửa
    }

    // Phương thức getform với tham số để chỉ định có lấy mahd hay không
    public Hopdong getform(boolean includeMahd) {
        Hopdong a = new Hopdong();

        // Chỉ set mahd nếu includeMahd = true (dùng cho sửa)
        if (includeMahd) {
            a.setMahd(lb_mahd.getText());
        }
        // Không set mahd khi thêm mới (includeMahd = false) vì SQL tự động tăng

        a.setManv(txt_manv.getText());

        // Chuyển đổi ngày từ dd/MM/yyyy sang yyyy-MM-dd cho SQL
        String ngayBatDau = convertDateToSQLFormat(txt_ngaybatdau.getText());
        String ngayKetThuc = convertDateToSQLFormat(txt_ngayketthuc.getText());
        a.setNgaybatdau(ngayBatDau);
        a.setNgayketthuc(ngayKetThuc);

        a.setLuongthoathuan(parseVND(txt_luongthoathuan.getText()));

        if (rd_conhieuluc.isSelected()) {
            a.setTrangthai("Còn hiệu lực");
        } else {
            a.setTrangthai("Hết hạn");
        }

        a.setNgaytao(lb_ngaytao.getText());
        a.setNguoitao(lb_nguoitao.getText());

        // Lấy mã loại hợp đồng từ combo box
        if (cbx_loaihopdong.getSelectedItem() != null) {
            String selectedItem = cbx_loaihopdong.getSelectedItem().toString();
            // Tìm mã loại hợp đồng tương ứng
            for (Loaihopdong lhd : listLoaiHD) {
                if (lhd.getTenloai().equals(selectedItem)) {
                    a.setMaloaihd(lhd.getMaloai());
                    break;
                }
            }
        }

        return a;
    }

    // Phương thức chuyển đổi ngày từ dd/MM/yyyy sang yyyy-MM-dd
    private String convertDateToSQLFormat(String dateStr) {
        if (dateStr == null || dateStr.trim().isEmpty()) {
            return "";
        }

        try {
            // Parse ngày từ format dd/MM/yyyy
            Date date = XDate.parse(dateStr.trim(), "dd/MM/yyyy");
            if (date != null) {
                // Format lại thành yyyy-MM-dd cho SQL
                return XDate.format(date, "yyyy-MM-dd");
            }
        } catch (Exception e) {
            // Nếu không parse được, thử format khác hoặc trả về chuỗi gốc
            try {
                // Thử parse từ format dd-MM-yyyy
                Date date = XDate.parse(dateStr.trim(), "dd-MM-yyyy");
                if (date != null) {
                    return XDate.format(date, "yyyy-MM-dd");
                }
            } catch (Exception ex) {
                // Nếu vẫn không parse được, trả về chuỗi gốc
            }
        }

        return dateStr.trim();
    }

    // Phương thức chuyển đổi ngày từ yyyy-MM-dd sang dd/MM/yyyy để hiển thị
    private String convertDateToDisplayFormat(String dateStr) {
        if (dateStr == null || dateStr.trim().isEmpty()) {
            return "";
        }

        try {
            // Parse ngày từ format yyyy-MM-dd (SQL format)
            Date date = XDate.parse(dateStr.trim(), "yyyy-MM-dd");
            if (date != null) {
                // Format lại thành dd/MM/yyyy để hiển thị
                return XDate.format(date, "dd/MM/yyyy");
            }
        } catch (Exception e) {
            // Nếu không parse được, thử format khác
            try {
                // Thử parse từ format dd/MM/yyyy (nếu dữ liệu cũ)
                Date date = XDate.parse(dateStr.trim(), "dd/MM/yyyy");
                if (date != null) {
                    return XDate.format(date, "dd/MM/yyyy");
                }
            } catch (Exception ex) {
                // Nếu vẫn không parse được, trả về chuỗi gốc
            }
        }

        return dateStr.trim();
    }

    public void setform(Hopdong b) {
        if (b == null) {
            return;
        }

        // Set basic information
        lb_mahd.setText(b.getMahd() != null ? b.getMahd() : "");
        txt_manv.setText(b.getManv() != null ? b.getManv() : "");
        lb_hoten.setText(b.getHoten() != null ? b.getHoten() : "");

        // Chuyển đổi ngày từ yyyy-MM-dd sang dd/MM/yyyy để hiển thị
        String ngayBatDauDisplay = convertDateToDisplayFormat(b.getNgaybatdau());
        String ngayKetThucDisplay = convertDateToDisplayFormat(b.getNgayketthuc());
        txt_ngaybatdau.setText(ngayBatDauDisplay);
        txt_ngayketthuc.setText(ngayKetThucDisplay);

        txt_luongthoathuan.setText(b.getLuongthoathuan() != null ? formatNumberWithCommas(b.getLuongthoathuan()) : "");

        // Set radio button based on status
        if (b.getTrangthai() != null && b.getTrangthai().equals("Còn hiệu lực")) {
            rd_conhieuluc.setSelected(true);
            rd_hethieuluc.setSelected(false);
        } else {
            rd_conhieuluc.setSelected(false);
            rd_hethieuluc.setSelected(true);
        }

        // Set creation information
        lb_ngaytao.setText(b.getNgaytao() != null ? b.getNgaytao() : "");
        lb_nguoitao.setText(b.getNguoitao() != null ? b.getNguoitao() : "");

        // Set combo box for contract type (handle both ID and Name values)
        if (b.getMaloaihd() != null) {
            boolean matched = false;
            for (Loaihopdong lhd : listLoaiHD) {
                if (lhd.getMaloai().equals(b.getMaloaihd())) {
                    cbx_loaihopdong.setSelectedItem(lhd.getTenloai());
                    matched = true;
                    break;
                }
            }
            if (!matched) {
                // If entity stores TenLoai instead of MaLoai, try selecting by name directly
                cbx_loaihopdong.setSelectedItem(b.getMaloaihd());
            }
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ

        list = dao.findAll(); // gọi DAO

        for (Hopdong lhd : list) {
            Object[] row = new Object[]{
                lhd.getMahd(),
                lhd.getManv(),
                lhd.getHoten(),
                lhd.getMaloaihd(), // Đây là tên loại hợp đồng từ query JOIN
                convertDateToDisplayFormat(lhd.getNgaybatdau()), // Chuyển đổi để hiển thị
                convertDateToDisplayFormat(lhd.getNgayketthuc()), // Chuyển đổi để hiển thị
                formatVND(lhd.getLuongthoathuan()),
                lhd.getTrangthai(),
                lhd.getNgaytao(),
                lhd.getNguoitao()

            };
            model.addRow(row);
        }
    }

    @Override
    public void edit() {
        int index = tb1.getSelectedRow();
        if (index >= 0 && index < list.size()) {
            Hopdong entity = list.get(index);
            this.setform(entity);
            tabs.setSelectedIndex(1);
        }
    }

    public void fillComboBox() {
        try {
            listLoaiHD = loaihdDao.findAll();
            String[] items = new String[listLoaiHD.size()];
            for (int i = 0; i < listLoaiHD.size(); i++) {
                // Hiển thị cả mã và tên loại hợp đồng
                items[i] = listLoaiHD.get(i).getTenloai();
            }
            cbx_loaihopdong.setModel(new DefaultComboBoxModel<>(items));

            // Tự động tính ngày khi có dữ liệu
            if (listLoaiHD.size() > 0) {
                calculateContractDates();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearForm() {
        lb_mahd.setText("(Tự động tạo)"); // Hiển thị thông báo mã sẽ tự động tạo
        txt_manv.setText("");
        lb_hoten.setText("");
        txt_ngaybatdau.setText("");
        txt_ngayketthuc.setText("");
        txt_luongthoathuan.setText("");
        rd_conhieuluc.setSelected(true); // Mặc định là còn hiệu lực
        rd_hethieuluc.setSelected(false);

        // Set ngày tạo và người tạo mặc định
        setDefaultCreationInfo();

        if (cbx_loaihopdong.getItemCount() > 0) {
            cbx_loaihopdong.setSelectedIndex(0);
            // Tự động tính ngày khi clear form
            calculateContractDates();
        }
    }

    public void calculateContractDates() {
        if (cbx_loaihopdong.getSelectedItem() != null && listLoaiHD != null && !listLoaiHD.isEmpty()) {
            String selectedItem = cbx_loaihopdong.getSelectedItem().toString();

            // Tìm loại hợp đồng được chọn
            Loaihopdong selectedContractType = null;
            for (Loaihopdong lhd : listLoaiHD) {
                if (lhd.getTenloai().equals(selectedItem)) {
                    selectedContractType = lhd;
                    break;
                }
            }

            if (selectedContractType != null) {
                // Chỉ set ngày bắt đầu nếu field đang trống hoặc form đang ở chế độ thêm mới
                if (txt_ngaybatdau.getText().trim().isEmpty() || lb_mahd.getText().equals("(Tự động tạo)")) {
                    Date currentDate = XDate.now();
                    String startDate = XDate.format(currentDate, "dd/MM/yyyy");
                    txt_ngaybatdau.setText(startDate);
                }

                // Tính ngày kết thúc dựa trên ngày bắt đầu hiện tại
                String startDateText = txt_ngaybatdau.getText().trim();
                if (!startDateText.isEmpty()) {
                    try {
                        Date startDate = XDate.parse(startDateText, "dd/MM/yyyy");
                        if (startDate != null) {
                            Calendar calendar = Calendar.getInstance();
                            calendar.setTime(startDate);
                            calendar.add(Calendar.MONTH, selectedContractType.getThoihan());
                            // Trừ đi 1 ngày từ ngày kết thúc
                            calendar.add(Calendar.DAY_OF_MONTH, -1);

                            Date endDate = calendar.getTime();
                            String endDateStr = XDate.format(endDate, "dd/MM/yyyy");
                            txt_ngayketthuc.setText(endDateStr);
                        }
                    } catch (Exception e) {
                        // Nếu không parse được ngày bắt đầu, sử dụng ngày hiện tại
                        Date currentDate = XDate.now();
                        Calendar calendar = Calendar.getInstance();
                        calendar.setTime(currentDate);
                        calendar.add(Calendar.MONTH, selectedContractType.getThoihan());

                        Date endDate = calendar.getTime();
                        String endDateStr = XDate.format(endDate, "dd/MM/yyyy");
                        txt_ngayketthuc.setText(endDateStr);
                    }
                }
            }
        }
    }

    // Phương thức tính lại ngày kết thúc khi thay đổi ngày bắt đầu
    public void calculateContractDatesFromStartDate() {
        if (cbx_loaihopdong.getSelectedItem() != null && listLoaiHD != null && !listLoaiHD.isEmpty()) {
            String selectedItem = cbx_loaihopdong.getSelectedItem().toString();

            // Tìm loại hợp đồng được chọn
            Loaihopdong selectedContractType = null;
            for (Loaihopdong lhd : listLoaiHD) {
                if (lhd.getTenloai().equals(selectedItem)) {
                    selectedContractType = lhd;
                    break;
                }
            }

            if (selectedContractType != null) {
                String startDateText = txt_ngaybatdau.getText().trim();
                if (!startDateText.isEmpty()) {
                    try {
                        Date startDate = XDate.parse(startDateText, "dd/MM/yyyy");
                        if (startDate != null) {
                            Calendar calendar = Calendar.getInstance();
                            calendar.setTime(startDate);
                            calendar.add(Calendar.MONTH, selectedContractType.getThoihan());
                            // Trừ đi 1 ngày từ ngày kết thúc
                            calendar.add(Calendar.DAY_OF_MONTH, -1);

                            Date endDate = calendar.getTime();
                            String endDateStr = XDate.format(endDate, "dd/MM/yyyy");
                            txt_ngayketthuc.setText(endDateStr);
                        }
                    } catch (Exception e) {
                        // Không làm gì nếu ngày không hợp lệ
                    }
                }
            }
        }
    }

    public String formatVND(String amount) {
        if (amount == null || amount.trim().isEmpty()) {
            return "0 VND";
        }

        try {
            // Loại bỏ các ký tự không phải số và dấu chấm
            String cleanAmount = amount.replaceAll("[^0-9.]", "");
            if (cleanAmount.isEmpty()) {
                return "0 VND";
            }

            // Nếu có dấu chấm, lấy phần trước dấu chấm
            if (cleanAmount.contains(".")) {
                cleanAmount = cleanAmount.split("\\.")[0];
            }

            if (cleanAmount.isEmpty()) {
                return "0 VND";
            }

            long number = Long.parseLong(cleanAmount);
            return String.format("%,d VND", number);
        } catch (NumberFormatException e) {
            return "0 VND";
        }
    }

    public String parseVND(String vndString) {
        if (vndString == null || vndString.trim().isEmpty()) {
            return "0";
        }

        // Loại bỏ "VND", dấu phẩy và các ký tự không phải số
        String cleanAmount = vndString.replaceAll("[^0-9]", "");
        return cleanAmount.isEmpty() ? "0" : cleanAmount;
    }

    public String formatNumberWithCommas(String number) {
        if (number == null || number.trim().isEmpty()) {
            return "0";
        }

        try {
            // Loại bỏ các ký tự không phải số và dấu chấm
            String cleanNumber = number.replaceAll("[^0-9.]", "");
            if (cleanNumber.isEmpty()) {
                return "0";
            }

            // Nếu có dấu chấm, lấy phần trước dấu chấm
            if (cleanNumber.contains(".")) {
                cleanNumber = cleanNumber.split("\\.")[0];
            }

            if (cleanNumber.isEmpty()) {
                return "0";
            }

            long num = Long.parseLong(cleanNumber);
            return String.format("%,d", num);
        } catch (NumberFormatException e) {
            return "0";
        }
    }

    // Bỏ chức năng lọc theo thời gian (theo yêu cầu)
    // Đã loại bỏ tất cả tiện ích lọc theo thời gian
    // Phương thức set thông tin tạo mặc định
    private void setDefaultCreationInfo() {
        // Set ngày tạo là ngày hiện tại
        Date currentDate = XDate.now();
        String currentDateStr = XDate.format(currentDate, "dd/MM/yyyy");
        lb_ngaytao.setText(currentDateStr);

        String currentUser = XAuth.user.getFullname();
        if (currentUser != null && !currentUser.trim().isEmpty()) {
            lb_nguoitao.setText(currentUser);
        } else {
            lb_nguoitao.setText("Admin"); // Fallback nếu không có thông tin user
        }
    }

    // Phương thức kiểm tra và lấy họ tên nhân viên
    private String getHoTenNhanVien(String maNV) {
        try {
            List<duan1.entity.nhanvien> listNV = nhanvienDao.findAll();
            for (duan1.entity.nhanvien nv : listNV) {
                if (nv.getMaNV() != null && nv.getMaNV().equals(maNV)) {
                    return nv.getHoTen();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // Phương thức cập nhật họ tên khi thay đổi mã nhân viên
    private void updateHoTenNhanVien() {
        String maNV = txt_manv.getText().trim();
        if (!maNV.isEmpty()) {
            String hoTen = getHoTenNhanVien(maNV);
            if (hoTen != null) {
                lb_hoten.setText(hoTen);
                lb_hoten.setForeground(java.awt.Color.BLACK);
            } else {
                lb_hoten.setText("Mã nhân viên không tồn tại");
                lb_hoten.setForeground(java.awt.Color.RED);
            }
        } else {
            lb_hoten.setText("");
        }
    }

    private void fillTable1() {
        DefaultTableModel model = (DefaultTableModel) tb2.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        try {
            Loaihopdongipml dao = new Loaihopdongipml();
            List<Hopdong> list = dao.sql1();

            for (Hopdong hd : list) {
                model.addRow(new Object[]{
                    hd.getManv(),
                    hd.getHoten(),
                    hd.getTenPhongBan(),
                    hd.getTenChucVu(),
                    hd.getTrangThaiHopDong()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void edit1() {
        int index = tb2.getSelectedRow();
        if (index < 0) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tb2.getModel();
        Object maNVObj = model.getValueAt(index, 0);
        Object hoTenObj = model.getValueAt(index, 1);

        String maNV = maNVObj != null ? maNVObj.toString() : "";
        String hoTen = hoTenObj != null ? hoTenObj.toString() : "";

        // Prepare form for creating a new contract for this employee
        lb_mahd.setText("(Tự động tạo)");
        txt_manv.setText(maNV);
        lb_hoten.setText(hoTen);
        lb_hoten.setForeground(java.awt.Color.BLACK);

        // Default status and creation info
        rd_conhieuluc.setSelected(true);
        rd_hethieuluc.setSelected(false);
        setDefaultCreationInfo();

        // Ensure a contract type is selected and auto-calc dates
        if (cbx_loaihopdong.getItemCount() > 0 && cbx_loaihopdong.getSelectedIndex() < 0) {
            cbx_loaihopdong.setSelectedIndex(0);
        }
        // Clear start date to let calculateContractDates set today automatically
        txt_ngaybatdau.setText("");
        txt_ngayketthuc.setText("");
        calculateContractDates();

        // Move to form tab
        tabs.setSelectedIndex(1);
    }

    public void timkiem() {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);

        String keyword = txt_timkiem.getText();
        if (keyword == null || keyword.trim().isEmpty()) {
            fillTable();
            return;
        }

        String search = normalizeForSearch(keyword);
        list = dao.findAll();

        for (Hopdong contract : list) {
            String fullName = contract.getHoten();
            if (fullName == null) {
                continue;
            }
            if (normalizeForSearch(fullName).contains(search)) {
                Object[] row = new Object[]{
                    contract.getMahd(),
                    contract.getManv(),
                    contract.getHoten(),
                    contract.getMaloaihd(),
                    convertDateToDisplayFormat(contract.getNgaybatdau()),
                    convertDateToDisplayFormat(contract.getNgayketthuc()),
                    formatVND(contract.getLuongthoathuan()),
                    contract.getTrangthai(),
                    contract.getNgaytao(),
                    contract.getNguoitao()
                };
                model.addRow(row);
            }
        }
    }

    private String normalizeForSearch(String input) {
        if (input == null) {
            return "";
        }
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFD)
                .replaceAll("\\p{M}+", "");
        return normalized.toLowerCase().trim();
    }
}
