/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.ipml.Loaihopdongipml;
import duan1.controller.loaihopdongcontroller;
import duan1.entity.Loaihopdong;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class LoaihopdongUI extends javax.swing.JDialog implements loaihopdongcontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoaihopdongUI.class.getName());
    private Loaihopdongipml dao = new Loaihopdongipml();
    private List<Loaihopdong> list = new ArrayList<>();

    /**
     * Creates new form LoaihopdongUI
     */
    public LoaihopdongUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tenloai = new javax.swing.JTextField();
        cbx_thoihan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lb_maloai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã loại", "Tên loại", "Thời hạn tháng", "Ghi Chú"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jLabel1.setText("Mã Loại");

        jLabel2.setText("Tên Loại");

        cbx_thoihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ", "3 ", "6 ", "12 ", "24 ", "36 ", " ", " ", " " }));

        jLabel3.setText("Thời Hạn");

        jLabel4.setText("Ghi chú");

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_ghichu);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xoá");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lb_maloai.setText("jLabel5");

        jLabel5.setText("Tháng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbx_thoihan, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2)
                        .addGap(62, 62, 62)
                        .addComponent(jButton3)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lb_maloai)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_thoihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.them();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.sua();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.xoa();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoaihopdongUI dialog = new LoaihopdongUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_thoihan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_maloai;
    private javax.swing.JTable tb1;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JTextField txt_tenloai;
    // End of variables declaration//GEN-END:variables

    @Override
    public void them() {
        // Kiểm tra dữ liệu đầu vào
        if (txt_tenloai.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên loại hợp đồng!");
            return;
        }
        
        Loaihopdong entity = this.getform();
        
        // Tạo mã loại hợp đồng tự động
        String newMaloai = generateMaloai();
        entity.setMaloai(newMaloai);
        
        try {
            dao.create(entity);
            this.fillTable();
            this.clearForm();
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage());
        }
    }

    @Override
    public void sua() {
        // Kiểm tra xem có đang edit hay không
        if (lb_maloai.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một loại hợp đồng để sửa!");
            return;
        }
        
        // Kiểm tra dữ liệu đầu vào
        if (txt_tenloai.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên loại hợp đồng!");
            return;
        }
        
        Loaihopdong entity = this.getform();
        entity.setMaloai(lb_maloai.getText());
        
        try {
            dao.update(entity);
            this.fillTable();
            this.clearForm();
            javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        }
    }

    @Override
    public void xoa() {
        // Kiểm tra xem có item nào được chọn không
        if (lb_maloai.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một loại hợp đồng để xóa!");
            return;
        }
        
        // Xác nhận xóa
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Bạn có chắc chắn muốn xóa loại hợp đồng này?", 
            "Xác nhận xóa", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                String id = lb_maloai.getText();
                dao.deleteById(id);
                this.fillTable();
                this.clearForm();
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
            }
        }
    }

    public Loaihopdong getform() {
        Loaihopdong a = new Loaihopdong();
        a.setTenloai(txt_tenloai.getText());
        
        // Kiểm tra và xử lý thoihan
        Object selectedItem = cbx_thoihan.getSelectedItem();
        if (selectedItem != null && !selectedItem.toString().trim().isEmpty()) {
            String thoihan = selectedItem.toString().trim();
            try {
                a.setThoihan(Integer.parseInt(thoihan));
            } catch (NumberFormatException e) {
                // Nếu không parse được, set giá trị mặc định
                a.setThoihan(1);
            }
        } else {
            a.setThoihan(1); // Giá trị mặc định
        }

        a.setGhichu(txt_ghichu.getText());

        return a;
    }

    public void setform(Loaihopdong b) {
        lb_maloai.setText(b.getMaloai());
        txt_tenloai.setText(b.getTenloai());
        // Find the correct index based on the thoihan value
        int thoihanValue = b.getThoihan();
        for (int i = 0; i < cbx_thoihan.getItemCount(); i++) {
            String item = cbx_thoihan.getItemAt(i);
            if (item != null && item.trim().equals(String.valueOf(thoihanValue))) {
                cbx_thoihan.setSelectedIndex(i);
                break;
            }
        }
        txt_ghichu.setText(b.getGhichu());
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ

         list = dao.findAll(); // gọi DAO

        for (Loaihopdong lhd : list) {
            Object[] row = new Object[]{
                lhd.getMaloai(),
                lhd.getTenloai(),
                lhd.getThoihan(),
                lhd.getGhichu()
            };
            model.addRow(row);
        }
    }

    @Override
    public void edit() {
        int index = tb1.getSelectedRow();
        if (index >= 0 && index < list.size()) {
            Loaihopdong entity = list.get(index);
            this.setform(entity);
        }
    }
    
    // Tạo mã loại hợp đồng tự động
    private String generateMaloai() {
        List<Loaihopdong> allLoaihopdong = dao.findAll();
        int maxNumber = 0;
        
        for (Loaihopdong lhd : allLoaihopdong) {
            String maloai = lhd.getMaloai();
            if (maloai != null && maloai.startsWith("LHD")) {
                try {
                    String numberStr = maloai.substring(3);
                    int number = Integer.parseInt(numberStr);
                    if (number > maxNumber) {
                        maxNumber = number;
                    }
                } catch (NumberFormatException e) {
                    // Bỏ qua nếu không parse được
                }
            }
        }
        
        return "LHD" + String.format("%03d", maxNumber + 1);
    }
    
    // Xóa form
    private void clearForm() {
        lb_maloai.setText("");
        txt_tenloai.setText("");
        cbx_thoihan.setSelectedIndex(0);
        txt_ghichu.setText("");
    }

}
