/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import duan1.DAO.ipml.NghiPhepipml;
import duan1.DAO.ipml.loainghiphepimpl;
import duan1.controller.nghiphepcontroller;
import duan1.entity.NghiPhep;
import duan1.entity.loainghiphep;
import duan1.util.XAuth;
import duan1.util.XDialog;
import java.awt.Color;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlynghiphepUI extends javax.swing.JDialog implements nghiphepcontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlynghiphepUI.class.getName());
    private javax.swing.JTextField currentTextField;
    private NghiPhepipml dao = new NghiPhepipml();
    private List<NghiPhep> nv = new ArrayList<>();

    /**
     * Creates new form quanlynghiphepUI
     */
    public quanlynghiphepUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        init1();
    }

    public void init() {
        getContentPane().setBackground(new Color(240, 240, 240));
        dateChooser1.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser1.hidePopup();
                }
            }

        });
    }

    public void init1() {
        fillTable();
        txt_mayeucau.setEnabled(false);
        fillcbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mayeucau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_ngaybatdau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ngayketthuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lydo = new javax.swing.JTextArea();
        bt_them = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbx_loainghiphep = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Ngày Bắt đầu", "Ngày kết thuc", "Lý do", "Loại Nghỉ", "Trạng Thái", "Ngày gửi", "Ngày xử lý", "Người xử lý", "Ghi chú xử lý", "Số ngày nghỉ"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách", jPanel1);

        jLabel1.setText("Mã yêu cầu");

        txt_mayeucau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mayeucauActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày Bắt đầu");

        jLabel3.setText("Ngày kết Thúc");

        jLabel4.setText("Lý Do");

        txt_lydo.setColumns(20);
        txt_lydo.setRows(5);
        jScrollPane1.setViewportView(txt_lydo);

        bt_them.setText("thêm");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_sua.setText("Sửa");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });

        bt_xoa.setText("Xoá");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton4FocusGained(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("...");
        jButton5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton5FocusGained(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cbx_loainghiphep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Loại Nghỉ Phép");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_them)
                .addGap(114, 114, 114)
                .addComponent(bt_sua)
                .addGap(108, 108, 108)
                .addComponent(bt_xoa)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_ngayketthuc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_mayeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_loainghiphep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_mayeucau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(cbx_loainghiphep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_them)
                    .addComponent(bt_sua)
                    .addComponent(bt_xoa))
                .addGap(73, 73, 73))
        );

        tabs.addTab("Yêu Cầu", jPanel2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Xin Nghỉ Phép");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        // TODO add your handling code here:
        this.sua();
        clearForm();
    }//GEN-LAST:event_bt_suaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Chọn ngày cho txt_ngaybatdau
        currentTextField = txt_ngaybatdau;
        dateChooser1.setTextRefernce(txt_ngaybatdau);
        dateChooser1.showPopup();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Chọn ngày cho txt_ngayketthuc
        currentTextField = txt_ngayketthuc;
        dateChooser1
                .setTextRefernce(txt_ngayketthuc);
        dateChooser1.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Xoá xử lý ở FocusGained cho cả hai nút
    private void jButton4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton4FocusGained
        // Không cần xử lý gì
    }//GEN-LAST:event_jButton4FocusGained

    private void jButton5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusGained
        // Không cần xử lý gì
    }//GEN-LAST:event_jButton5FocusGained

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:
        this.them();
        clearForm();
    }//GEN-LAST:event_bt_themActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        // TODO add your handling code here:
        this.xoa();
        clearForm();
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        this.edit();
    }//GEN-LAST:event_tb1MouseClicked

    private void txt_mayeucauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mayeucauActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_mayeucauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlynghiphepUI dialog = new quanlynghiphepUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JComboBox<String> cbx_loainghiphep;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tb1;
    private javax.swing.JTextArea txt_lydo;
    private javax.swing.JTextField txt_mayeucau;
    private javax.swing.JTextField txt_ngaybatdau;
    private javax.swing.JTextField txt_ngayketthuc;
    // End of variables declaration//GEN-END:variables

    public NghiPhep getForm() {
        NghiPhep np = new NghiPhep();

        // Gán mã yêu cầu nếu có (chế độ sửa)
        String idText = txt_mayeucau.getText().trim();
        if (!idText.isEmpty()) {
            try {
                np.setMayeucau(idText);
            } catch (NumberFormatException e) {
                XDialog.alert("❌ Mã yêu cầu không hợp lệ.");
                return null;
            }
        }

        // Gán mã nhân viên đang đăng nhập
        np.setManv(XAuth.user.getMaNV());

        // Xử lý định dạng ngày
        try {
            String inputNgayBD = txt_ngaybatdau.getText().trim().replace("/", "-");
            String inputNgayKT = txt_ngayketthuc.getText().trim().replace("/", "-");

            LocalDate dateBD, dateKT;

            DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            if (inputNgayBD.matches("\\d{2}-\\d{2}-\\d{4}")) {
                dateBD = LocalDate.parse(inputNgayBD, formatter1);
            } else if (inputNgayBD.matches("\\d{4}-\\d{2}-\\d{2}")) {
                dateBD = LocalDate.parse(inputNgayBD, formatter2);
            } else {
                throw new DateTimeParseException("Sai định dạng ngày bắt đầu", inputNgayBD, 0);
            }

            if (inputNgayKT.matches("\\d{2}-\\d{2}-\\d{4}")) {
                dateKT = LocalDate.parse(inputNgayKT, formatter1);
            } else if (inputNgayKT.matches("\\d{4}-\\d{2}-\\d{2}")) {
                dateKT = LocalDate.parse(inputNgayKT, formatter2);
            } else {
                throw new DateTimeParseException("Sai định dạng ngày kết thúc", inputNgayKT, 0);
            }

            np.setNgaybatdau(Date.valueOf(dateBD));
            np.setNgayketthuc(Date.valueOf(dateKT));
        } catch (DateTimeParseException e) {
            XDialog.alert("❌ Lỗi định dạng ngày. Nhập đúng dạng dd-MM-yyyy hoặc yyyy-MM-dd");
            return null;
        }

        np.setLydo(txt_lydo.getText().trim());
        np.setMaloai(cbx_loainghiphep.getSelectedIndex() + 1); // Giả sử index + 1 là đúng mã loại

        return np;
    }

    public void setForm(NghiPhep np) {
        txt_mayeucau.setText(String.valueOf(np.getMayeucau()));
        txt_ngaybatdau.setText(np.getNgaybatdau().toString());
        txt_ngayketthuc.setText(np.getNgayketthuc().toString());
        txt_lydo.setText(np.getLydo());

        // Gán lại combobox theo tên loại nếu cần
        if (np.getTenloai() != null) {
            cbx_loainghiphep.setSelectedItem(np.getTenloai());
        }
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        String manv = XAuth.user.getMaNV();
        nv = dao.findall(manv); // Lấy danh sách theo nhân viên

        for (NghiPhep np : nv) {
            Object[] row = {
                np.getMayeucau(),
                np.getNgaybatdau(),
                np.getNgayketthuc(),
                np.getLydo(),
                np.getTenloai(),
                np.getTrangthai(),
                np.getNgaygui(),
                np.getNgayxuly(),
                np.getNguoixuly(),
                np.getGhichuxuly(),
                np.getSongaynghi()
            };
            model.addRow(row);
        }
    }

    @Override
    public void them() {
        NghiPhep entity = this.getForm();
        if (entity == null) {
            return;
        }

        dao.create(entity);
        this.fillTable();
        XDialog.alert("✅ Thêm mới thành công");
    }

    @Override
    public void sua() {
        NghiPhep entity = this.getForm();
        if (entity == null) {
            XDialog.alert("❌ Dữ liệu không hợp lệ. Không thể cập nhật.");
            return;
        }

        dao.update(entity);
        this.fillTable();
        XDialog.alert("✅ Cập nhật thành công");
    }

    @Override
    public void xoa() {
        String id = txt_mayeucau.getText().trim();
        try {
            dao.deleteById(Integer.parseInt(id));
            this.fillTable();
            XDialog.alert("✅ Xóa thành công");
        } catch (NumberFormatException e) {
            XDialog.alert("❌ Mã yêu cầu không hợp lệ.");
        }
    }

    @Override
    public void edit() {
        int index = tb1.getSelectedRow();
        if (index < 0) {
            XDialog.alert("❗ Vui lòng chọn một dòng để sửa.");
            return;
        }

        NghiPhep entity = nv.get(index);
        this.setForm(entity);
        tabs.setSelectedIndex(1);
    }

    public void clearForm() {
        txt_mayeucau.setText("");
        txt_ngaybatdau.setText("");
        txt_ngayketthuc.setText("");
        txt_lydo.setText("");
        cbx_loainghiphep.setSelectedIndex(0);
        tb1.clearSelection();
    }

    public void fillcbx() {
        List<loainghiphep> list = new loainghiphepimpl().findAll();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (loainghiphep item : list) {
            model.addElement(item.getTenloai());
        }

        cbx_loainghiphep.setModel(model);
    }
}
