/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.ipml.NghiPhepipml;
import duan1.DAO.ipml.loainghiphepimpl;
import duan1.controller.nghiphepcontroller;
import duan1.entity.NghiPhep;
import duan1.entity.loainghiphep;
import duan1.util.XAuth;
import duan1.util.XDialog;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlynghiphep1UI extends javax.swing.JDialog implements nghiphepcontroller{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlynghiphep1UI.class.getName());
      private List<NghiPhep> list = new ArrayList<>();
     private NghiPhepipml dao = new NghiPhepipml();
    /**
     * Creates new form quanlynghiphep1UI
     */
    public quanlynghiphep1UI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    public void init(){
    fillTable();
        fillcbx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mayeucau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        txt_ngaybatdau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ngayketthhuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ngaygui = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_lydo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rd_tuchoi = new javax.swing.JRadioButton();
        rd_duyet = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_nguoixuly = new javax.swing.JLabel();
        lb_ngayxuly = new javax.swing.JLabel();
        txt_ghichuxuly = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbx_loainghiphep = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nghỉ Phép", "Mã NV", "Loại nghỉ", "Họ tên", "Ngày Bắt đầu", "Ngày kết thuc", "Lý do", "Trạng Thái", "Ngày Gửi", "Ngày xử lý", "Người xử lý", "Ghi chú xử lý"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Danh Sách", jPanel1);

        jLabel1.setText("Mã yêu cầu");

        jLabel2.setText("Họ tên");

        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày bắt đầu");

        jLabel4.setText("Ngày kết thúc");

        jLabel5.setText("Ngày gửi");

        jLabel7.setText("Lý do");

        jLabel8.setText("Trạng thái");

        buttonGroup1.add(rd_tuchoi);
        rd_tuchoi.setText("Từ chối");
        rd_tuchoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_tuchoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_duyet);
        rd_duyet.setText("Duyệt");
        rd_duyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_duyetActionPerformed(evt);
            }
        });

        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Người xử lý");

        jLabel12.setText("Ngày xử lý");

        lb_nguoixuly.setText("jLabel10");

        lb_ngayxuly.setText("jLabel11");

        jLabel10.setText("Ghi chú xử lý");

        cbx_loainghiphep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Loại nghỉ phép");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ngayketthhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mayeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ngaygui, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rd_duyet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rd_tuchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ghichuxuly, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ngayxuly, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nguoixuly, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_loainghiphep, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 165, 165))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_mayeucau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd_tuchoi))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ngayketthhuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)
                                .addComponent(lb_ngayxuly)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lb_nguoixuly)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ghichuxuly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(19, 19, 19)
                                .addComponent(rd_duyet)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ngaygui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addGap(7, 7, 7)
                        .addComponent(cbx_loainghiphep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        tabs.addTab("Nghỉ Phép", jPanel2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Quản Lý Nghỉ Phép");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
  this.edit();
  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String ngayHienTai = sdf.format(new Date());

            // Set lên label
            lb_ngayxuly.setText(ngayHienTai);
    }//GEN-LAST:event_tb1MouseClicked

    private void rd_tuchoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_tuchoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_tuchoiActionPerformed

    private void rd_duyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_duyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_duyetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.sua();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlynghiphep1UI dialog = new quanlynghiphep1UI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_loainghiphep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_ngayxuly;
    private javax.swing.JLabel lb_nguoixuly;
    private javax.swing.JRadioButton rd_duyet;
    private javax.swing.JRadioButton rd_tuchoi;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txt_ghichuxuly;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_lydo;
    private javax.swing.JTextField txt_mayeucau;
    private javax.swing.JTextField txt_ngaybatdau;
    private javax.swing.JTextField txt_ngaygui;
    private javax.swing.JTextField txt_ngayketthhuc;
    // End of variables declaration//GEN-END:variables

public void fillTable() {
    DefaultTableModel model = (DefaultTableModel) tb1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

    list = dao.findAll(); // Lấy toàn bộ danh sách nghỉ phép

    for (NghiPhep np : list) {
        Object[] row = {
            np.getMayeucau(),
            np.getManv(),
            np.getTenloai(),
            np.getHoten(),
            np.getNgaybatdau(),
            np.getNgayketthuc(),
            np.getLydo(),
            np.getTrangthai(),
            np.getNgaygui(),
            np.getNgayxuly(),
            np.getNguoixuly(),
            np.getGhichuxuly()
        };
        model.addRow(row);
    }
}

public NghiPhep getForm() {
    NghiPhep np = new NghiPhep();

    try {
        np.setMayeucau(txt_mayeucau.getText());
    } catch (NumberFormatException e) {
        XDialog.alert("❌ Mã yêu cầu không hợp lệ!");
        return null;
    }

    np.setLydo(txt_lydo.getText().trim());
    np.setTrangthai(rd_duyet.isSelected() ? "Đã duyệt" : "Từ chối");

    String now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    np.setNgayxuly(now);
    np.setNguoixuly(XAuth.user.getFullname());
    np.setGhichuxuly(txt_ghichuxuly.getText().trim());
     cbx_loainghiphep.setSelectedIndex(np.getMaloai()- 1);
    return np;
}

public void setForm(NghiPhep np) {
    txt_mayeucau.setText(String.valueOf(np.getMayeucau()));
    txt_hoten.setText(np.getHoten());

    if (np.getNgaybatdau() != null) {
        txt_ngaybatdau.setText(np.getNgaybatdau().toString());
    }

    if (np.getNgayketthuc() != null) {
        txt_ngayketthhuc.setText(np.getNgayketthuc().toString());
    }

    txt_lydo.setText(np.getLydo());
    txt_ngaygui.setText(np.getNgaygui());
  

    if ("Đã duyệt".equalsIgnoreCase(np.getTrangthai())) {
        rd_duyet.setSelected(true);
    } else {
        rd_tuchoi.setSelected(true);
    }

    lb_ngayxuly.setText(np.getNgayxuly());
    lb_nguoixuly.setText(np.getNguoixuly());
}

@Override
public void them() {
    NghiPhep entity = this.getForm();
    if (entity == null) return;

    dao.create(entity);
    this.fillTable();
    XDialog.alert("✅ Thêm mới thành công");
}

@Override
public void sua() {
    NghiPhep entity = this.getForm();
    if (entity == null) {
        XDialog.alert("❌ Không thể cập nhật vì dữ liệu không hợp lệ.");
        return;
    }

    dao.update(entity);
    this.fillTable();
    XDialog.alert("✅ Cập nhật thành công");
}

@Override
public void xoa() {
    String id = txt_mayeucau.getText();
    try {
        dao.deleteById(Integer.valueOf(id));
        this.fillTable();
        XDialog.alert("✅ Xoá thành công");
    } catch (NumberFormatException e) {
        XDialog.alert("❌ Mã yêu cầu không hợp lệ!");
    }
}

@Override
public void edit() {
    int index = tb1.getSelectedRow();
    if (index < 0) {
        XDialog.alert("❗ Vui lòng chọn một dòng để chỉnh sửa.");
        return;
    }

    NghiPhep entity = list.get(index);
    this.setForm(entity);
    tabs.setSelectedIndex(1);
}

public void clearForm() {
    txt_mayeucau.setText("");
    txt_hoten.setText("");
    txt_ngaybatdau.setText("");
    txt_ngayketthhuc.setText("");
    txt_lydo.setText("");
    txt_ngaygui.setText("");
    
    txt_ghichuxuly.setText("");
    lb_ngayxuly.setText("");
    lb_nguoixuly.setText("");
    buttonGroup1.clearSelection();
    tb1.clearSelection();
}

public void fillcbx() {
    List<loainghiphep> list = new loainghiphepimpl().findAll();
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    for (loainghiphep item : list) {
        model.addElement(item.getTenloai());
    }

    cbx_loainghiphep.setModel(model);
}
}
