/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.chamcongDAO;
import duan1.DAO.ipml.quanlychamcongimpl;
import duan1.controller.quanlychamcongcontroller;
import duan1.entity.Thongkechamcong;
import duan1.entity.chamcong;
import duan1.util.XDialog;
import java.awt.Frame;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlychamcongui1 extends javax.swing.JDialog implements quanlychamcongcontroller {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlychamcongui1.class.getName());
    private List<chamcong> nv = new ArrayList<>();
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private chamcongDAO dao = new quanlychamcongimpl();
    private String maNV;

    /**
     * Creates new form form3
     */
    public quanlychamcongui1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    public quanlychamcongui1(java.awt.Window parent, boolean modal,
            String maCC,String maNV, String hoTen, String checkin, String checkout,
            String tongGio, String diLam, String ngay, String ghiChu) {
        super(parent, ModalityType.APPLICATION_MODAL); // dùng constructor của JDialog với Window
        initComponents();
        
        this.maNV = maNV;
        txt_maCC.setText(maCC);
        txt_manv.setText(maNV);
        txt_hoten.setText(hoTen);
        txt_checkin.setText(checkin);
        txt_checkout.setText(checkout);
        txt_tonggio.setText(tongGio);
        
        if (diLam.equalsIgnoreCase("có")) {
            rd_ko.setSelected(false);
            rd_co.setSelected(true);
        } else {
            rd_ko.setSelected(true);
            rd_co.setSelected(false);
        }
        
        txt_ngay.setText(ngay);
        txt_ghichu.setText(ghiChu);
        
        setLocationRelativeTo(parent);
        fillTable();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_checkout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tonggio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ngay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_ghichu = new javax.swing.JTextField();
        rd_co = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_checkin = new javax.swing.JTextField();
        rd_ko = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_maCC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Tổng giờ");

        jLabel6.setText("Đi làm");

        jLabel7.setText("Ngày ");

        jLabel8.setText("Ghi Chú");

        buttonGroup1.add(rd_co);
        rd_co.setText("Có");

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Đi Muộn", "Về Sớm", "Nghỉ lế", "Nghỉ Phép", "Nghỉ Không Phép"
            }
        ));
        jScrollPane3.setViewportView(tb2);

        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Checkin");

        buttonGroup1.add(rd_ko);
        rd_ko.setText("Không");

        jLabel4.setText("Checkout");

        jButton2.setText("Xoá");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã chấn công");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maCC, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton2))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rd_co, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rd_ko, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_tonggio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_tonggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_co)
                    .addComponent(rd_ko))
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_maCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.xoa();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlychamcongui1 dialog = new quanlychamcongui1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rd_co;
    private javax.swing.JRadioButton rd_ko;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField txt_checkin;
    private javax.swing.JTextField txt_checkout;
    private javax.swing.JTextField txt_ghichu;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_maCC;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_ngay;
    private javax.swing.JTextField txt_tonggio;
    // End of variables declaration//GEN-END:variables

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tb2.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        try {
            // Dùng biến maNV đã truyền từ constructor
            LocalDate now = LocalDate.now();
            int thang = now.getMonthValue();
            int nam = now.getYear();
              System.out.println("maNV = " + maNV + ", thang = " + thang + ", nam = " + nam);
            
            Thongkechamcong tk = dao.thongkechamcong(maNV, thang, nam);
            
            if (tk != null) {
                model.addRow(new Object[]{
                    tk.getDiMuon(),
                    tk.getVeSom(),
                    tk.getNghiLe(),
                    tk.getNghiPhep(),
                    tk.getNghiKhongPhep()
                });
            } else {
               
            }
        } catch (Exception e) {
            e.printStackTrace();
            XDialog.alert("Lỗi khi thống kê: " + e.getMessage());
        }
      

    }
    
    public chamcong getform() {
    chamcong a = new chamcong();

    String strMaNV = txt_manv.getText().trim();
    if (strMaNV.isEmpty()) {
        XDialog.alert("Mã nhân viên không được để trống!");
        return null;
    }

    try {
       String ma = strMaNV;
        a.setMaNV(ma);
    } catch (NumberFormatException e) {
        e.printStackTrace();
        XDialog.alert("Mã nhân viên không hợp lệ!");
        return null;
    }

    a.setHoten(txt_hoten.getText());

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        Time checkin = new Time(sdf.parse(txt_checkin.getText()).getTime());
        Time checkout = new Time(sdf.parse(txt_checkout.getText()).getTime());
        a.setCheckIn(checkin);
        a.setCheckOut(checkout);
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Check-in / Check-out sai định dạng! (HH:mm)");
        return null;
    }

    a.setDiLam(rd_co.isSelected());

    // Ngày làm việc
    try {
        String strNgay = txt_ngay.getText().trim();
        if (strNgay.isEmpty()) {
            XDialog.alert("Ngày làm việc không được để trống!");
            return null;
        }

        java.sql.Date ngay = java.sql.Date.valueOf(strNgay); // yêu cầu yyyy-MM-dd
        a.setNgay(ngay);
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Ngày làm việc sai định dạng! (yyyy-MM-dd)");
        return null;
    }

    a.setGhiChu(txt_ghichu.getText());

    return a;
}

    
    @Override
    public void them() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
   @Override
public void sua() {
    chamcong entity = this.getform(); // Lấy dữ liệu từ form

    if (entity == null) {
        XDialog.alert("Dữ liệu nhập không hợp lệ!");
        return;
    }

    try {
        // Hỏi xác nhận trước khi cập nhật
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc chắn muốn cập nhật bản ghi chấm công này?", 
                "Xác nhận cập nhật", 
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        dao.update(entity);           // Cập nhật vào CSDL
        XDialog.alert("Cập nhật thành công!");
        this.fillTable();            // Load lại dữ liệu bảng
                        // Nếu có phương thức clear
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Cập nhật thất bại: " + e.getMessage());
    }
}


    
  @Override
public void xoa() {
    String id = txt_maCC.getText().trim();

    // Kiểm tra rỗng
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn bản ghi cần xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int maCC = Integer.parseInt(id);

        // Xác nhận trước khi xóa
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa mã chấm công " + maCC + "?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dao.deleteById(maCC);  // Xóa trong DAO
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            this.fillTable();      // Refresh bảng
                // Nếu có method clear
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Mã chấm công không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}

    
    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
    }
    
}
