/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.DAO.chamcongDAO;
import duan1.DAO.ipml.quanlychamcongimpl;
import duan1.UI.quanlychamcongui1;
import duan1.UI.quanlychamcongui2;
import duan1.controller.quanlychamcongcontroller;
import duan1.entity.chamcong;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlychamcongui extends javax.swing.JDialog implements quanlychamcongcontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlychamcongui.class.getName());
    private List<chamcong> nv = List.of();
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private quanlychamcongimpl repo = new quanlychamcongimpl();
    private chamcongDAO dao = new quanlychamcongimpl();
       private Timer timer;

    /**
     * Creates new form quanlychamcongui
     */
    public quanlychamcongui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        defaultTableModel = (DefaultTableModel) tb1.getModel();
         filltbale(); 
       // Gọi trong constructor hoặc khi mở form
        Timer timer = new Timer(500, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
                filltbale(); // Gọi lại fillTable mỗi 5 giây
            }
        });
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        txt_timkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setText("Tìm Kiếm");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "mã nv", "Họ Và tên", "Checkin", "Checkout", "Tổng giờ", "Đi Làm", "Ngày", "Ghi chú"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm Chấm Công");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ CHẤM CÔNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int row = tb1.getSelectedRow();
        if (row != -1) {
            Object objMaCC = tb1.getValueAt(row, 0);
            Object objMaNV = tb1.getValueAt(row, 1);
            Object objHoTen = tb1.getValueAt(row, 2);
            Object objCheckin = tb1.getValueAt(row, 3);
            Object objCheckout = tb1.getValueAt(row, 4);
            Object objTongGio = tb1.getValueAt(row, 5);
            Object objDiLam = tb1.getValueAt(row, 6);
            Object objNgay = tb1.getValueAt(row, 7);
            Object objGhiChu = tb1.getValueAt(row, 8);

            String maCC = objMaCC != null ? objMaCC.toString() : "";
            String maNV = objMaNV != null ? objMaNV.toString() : "";
            String hoTen = objHoTen != null ? objHoTen.toString() : "";
            String checkin = objCheckin != null ? objCheckin.toString() : "";
            String checkout = objCheckout != null ? objCheckout.toString() : "";
            String tongGio = objTongGio != null ? objTongGio.toString() : "";
            String diLam = objDiLam != null ? objDiLam.toString() : "";
            String ngay = objNgay != null ? objNgay.toString() : "";
            String ghiChu = objGhiChu != null ? objGhiChu.toString() : "";

            // Lấy form cha (đang là JDialog hoặc JPanel nằm trong JDialog)
            Window parentWindow = SwingUtilities.getWindowAncestor(this);
            if (parentWindow != null) {
                parentWindow.setVisible(false); // Ẩn form cha
            }

            // Mở form con (form3)
            quanlychamcongui1 dialog = new quanlychamcongui1(
                    parentWindow, // truyền form cha để làm owner
                    true, // modal
                    maCC, maNV, hoTen, checkin, checkout, tongGio, diLam, ngay, ghiChu
            );
            dialog.setLocationRelativeTo(null); // căn giữa màn hình (tuỳ chọn)
            dialog.setVisible(true); // show form con, sẽ block tại đây nếu modal

            // Sau khi form con đóng, hiện lại form cha (nếu cần)
            if (parentWindow != null) {
                parentWindow.setVisible(true);
            }
        }

    }//GEN-LAST:event_tb1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        timkiem();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Gọi từ trong class quanlychamcongui (extends JDialog)
        this.setVisible(false); // Ẩn form cha

        quanlychamcongui2 dialog = new quanlychamcongui2(this, true); // Tạo form con, truyền "this" để biết ai là cha
        dialog.setLocationRelativeTo(this); // Căn giữa theo form cha
        dialog.setVisible(true); // Mở form con (modal sẽ chặn cha cho đến khi đóng)

        this.setVisible(true); // Khi form con đóng lại → hiện lại form cha


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlychamcongui dialog = new quanlychamcongui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void them() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void sua() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void xoa() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void filltbale() {
        nv = dao.findAll();
        defaultTableModel.setRowCount(0);

        for (chamcong list : nv) {
            defaultTableModel.addRow(new Object[]{
                list.getMaChamCong(),
                list.getMaNV(),
                list.getHoten(),
                list.getCheckIn(),
                list.getCheckOut(),
                list.getTongGio(),
                list.isDiLam() ? "Có" : "Không",
                list.getNgay(),
                list.getGhiChu()
            });
        }
    }

   public void timkiem() {
    if (timer != null) timer.stop(); // ✅ tránh NullPointerException

    String ten = txt_timkiem.getText().trim().toLowerCase();
    defaultTableModel.setRowCount(0);

    for (chamcong list : nv) {
        if (list.getHoten().toLowerCase().contains(ten)) {
            defaultTableModel.addRow(new Object[]{
                list.getMaChamCong(),
                list.getMaNV(),
                list.getHoten(),
                list.getCheckIn(),
                list.getCheckOut(),
                list.getTongGio(),
                list.isDiLam() ? "Có" : "Không",
                list.getNgay(),
                list.getGhiChu()
            });
        }
    }

    if (timer != null) timer.start(); // ✅ bật lại nếu timer tồn tại
}


    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
