/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;

import duan1.controller.QuanLyLuongControlner;
import duan1.entity.QuanLyLuong;
import duan1.manager.ChitietluongManager;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.List;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class quanlyluongUI extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(quanlyluongUI.class.getName());
    QuanLyLuongControlner controller = new QuanLyLuongControlner();
    /**
     * Creates new form quanlyluongUI
     */
    public quanlyluongUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        init();
    }
    
    public void init(){
        // Set mặc định cho combobox là tháng hiện tại
        Calendar cal = Calendar.getInstance();
        int currentMonth = cal.get(Calendar.MONTH) + 1; // Tháng hiện tại (1-12)
        int currentYear = cal.get(Calendar.YEAR);
        
        // Cập nhật combobox với tháng hiện tại
        cbx_loc.setSelectedItem("Tháng " + currentMonth + " năm " + currentYear);
        
        // Thêm event listener cho combobox
        cbx_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_locActionPerformed(evt);
            }
        });
        
        // Lọc dữ liệu theo tháng hiện tại khi khởi tạo
        try {
            List<QuanLyLuong> list = controller.getLuongTheoThangNam(currentMonth, currentYear);
            fillTableWithData(list);
        } catch (Exception e) {
            fillTable(); // Nếu có lỗi thì hiển thị tất cả
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_bang = new javax.swing.JTable();
        cbx_loc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Lương");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");

        txt_hoten.setBackground(new java.awt.Color(204, 255, 255));

        btn_timkiem.setBackground(new java.awt.Color(51, 255, 255));
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jtb_bang.setBackground(new java.awt.Color(204, 255, 204));
        jtb_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Mã Lương", "Họ tên", "Tháng", "Năm", "Lương cơ bản ", "Lương phụ cấp ", "Thưởng ", "Khấu Trừ", "Tổng Lương"
            }
        ));
        jtb_bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_bang);

        cbx_loc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 tháng qua", "6 tháng qua", "Năm nay", "Năm ngoái", "Tất cả" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276)
                                .addComponent(cbx_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(109, 109, 109)
                        .addComponent(btn_timkiem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maluongActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        try {
            String hoTen = txt_hoten.getText().trim();
            
            if (hoTen.isEmpty()) {
                // Nếu không nhập gì thì hiển thị tất cả
                fillTable();
                return;
            }
            
            // Tạo model cho JTable
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{
                "Mã NV", "Mã Lương", "Họ tên", "Tháng", "Năm",
                "Lương cơ bản", "Lương phụ cấp", "Thưởng", "Khấu Trừ", "Tổng Lương"
            });
            
            // Gọi controller để tìm kiếm theo tên
            List<QuanLyLuong> list = controller.searchLuongByHoTenOnly(hoTen);
            
            // Đổ dữ liệu vào bảng
            for (QuanLyLuong l : list) {
                model.addRow(new Object[]{
                    l.getManv(),
                    l.getMaluong(),
                    l.getHoten(),
                    l.getThang(),
                    l.getNam(),
                    formatVND(l.getLuongcoban()),
                    formatVND(l.getLuongphucap()),
                    formatVND(l.getThuong()),
                    formatVND(l.getKhautru()),
                    formatVND(l.getTongluong())
                });
            }
            
            // Gán model vào JTable
            jtb_bang.setModel(model);
            
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có tên: " + hoTen);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void jtb_bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_bangMouseClicked
        int selectedRow = jtb_bang.getSelectedRow();
        if (selectedRow >= 0) {
            String maNV = String.valueOf(jtb_bang.getValueAt(selectedRow, 0));
            int thang = Integer.parseInt(String.valueOf(jtb_bang.getValueAt(selectedRow, 3)));
            int nam = Integer.parseInt(String.valueOf(jtb_bang.getValueAt(selectedRow, 4)));

            ChitietluongManager dialog = new ChitietluongManager(new javax.swing.JFrame(), true);
            dialog.loadPhieuLuongChiTiet(maNV, thang, nam);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jtb_bangMouseClicked

    private void cbx_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_locActionPerformed
        try {
            String selectedOption = (String) cbx_loc.getSelectedItem();
            List<QuanLyLuong> list = null;
            
            if (selectedOption != null) {
                switch (selectedOption) {
                    case "3 tháng qua":
                        list = controller.getLuong3ThangQua();
                        break;
                    case "6 tháng qua":
                        list = controller.getLuong6ThangQua();
                        break;
                    case "Năm nay":
                        list = controller.getLuongNamNay();
                        break;
                    case "Năm ngoái":
                        list = controller.getLuongNamNgoai();
                        break;
                    case "Tất cả":
                        list = controller.laytatcabangluong();
                        break;
                    default:
                        // Nếu là "Tháng X năm Y"
                        if (selectedOption.startsWith("Tháng ")) {
                            String[] parts = selectedOption.split(" ");
                            if (parts.length >= 4) {
                                int month = Integer.parseInt(parts[1]);
                                int year = Integer.parseInt(parts[3]);
                                list = controller.getLuongTheoThangNam(month, year);
                            }
                        }
                        break;
                }
            }
            
            if (list != null) {
                fillTableWithData(list);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi lọc dữ liệu: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbx_locActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                quanlyluongUI dialog = new quanlyluongUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbx_loc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb_bang;
    private javax.swing.JTextField txt_hoten;
    // End of variables declaration//GEN-END:variables




   public void fillTable() {
    try {
        // Tạo model cho JTable
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã NV", "Mã Lương", "Họ tên", "Tháng", "Năm",
            "Lương cơ bản", "Lương phụ cấp", "Thưởng", "Khấu Trừ", "Tổng Lương"
        });

        // Gọi controller để lấy danh sách lương
        List<QuanLyLuong> list = controller.laytatcabangluong(); 

        // Đổ dữ liệu vào bảng
        for (QuanLyLuong l : list) {
            model.addRow(new Object[]{
                l.getManv(),
                l.getMaluong(),
                l.getHoten(),
                l.getThang(),
                l.getNam(),
                formatVND(l.getLuongcoban()),
                formatVND(l.getLuongphucap()),
                formatVND(l.getThuong()),
                formatVND(l.getKhautru()),
                formatVND(l.getTongluong())
            });
        }

        // Gán model vào JTable
        jtb_bang.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu bảng lương: " + e.getMessage());
        e.printStackTrace();
    }
}

public void fillTableWithData(List<QuanLyLuong> list) {
    try {
        // Tạo model cho JTable
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Mã NV", "Mã Lương", "Họ tên", "Tháng", "Năm",
            "Lương cơ bản", "Lương phụ cấp", "Thưởng", "Khấu Trừ", "Tổng Lương"
        });

        // Đổ dữ liệu vào bảng
        for (QuanLyLuong l : list) {
            model.addRow(new Object[]{
                l.getManv(),
                l.getMaluong(),
                l.getHoten(),
                l.getThang(),
                l.getNam(),
                formatVND(l.getLuongcoban()),
                formatVND(l.getLuongphucap()),
                formatVND(l.getThuong()),
                formatVND(l.getKhautru()),
                formatVND(l.getTongluong())
            });
        }

        // Gán model vào JTable
        jtb_bang.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu bảng lương: " + e.getMessage());
        e.printStackTrace();
    }
}




    private String formatVND(BigDecimal amount) {
        if (amount == null) {
            return "";
        }
        BigDecimal truncated = amount.setScale(0, RoundingMode.DOWN); // Bỏ phần lẻ (ví dụ 4 số sau dấu .)
        NumberFormat vnCurrency = NumberFormat.getCurrencyInstance(Locale.forLanguageTag("vi-VN"));
        vnCurrency.setMaximumFractionDigits(0);
        vnCurrency.setMinimumFractionDigits(0);
        return vnCurrency.format(truncated);
    }

}
