/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.UI;


import duan1.DAO.TTCaNhanDAO;
import duan1.DAO.ipml.TTCaNhanDAOimpl;
import duan1.controller.ThongTinController;
import duan1.entity.ThongTin;
import duan1.util.XAuth;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.*;


/**
 *
 * @author xloc2
 */
public class ThongTinCaNhan extends javax.swing.JDialog implements ThongTinController {
    
    private ThongTin thongTin;
    private TTCaNhanDAO dao = new TTCaNhanDAOimpl();
    private List<ThongTin> items = new ArrayList<>();

    /**
     * Creates new form ThongTinCaNhan
     */
    public ThongTinCaNhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setForm();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbotrangthai = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtten = new javax.swing.JLabel();
        txtmaphong = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtgioitinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtngayvao = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtchucvu = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txttrinhdo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtchuyennghanh = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtnguoitao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_anh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Cá Nhân");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Nhân Viên");

        txtmanv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmanv.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Trạng Thái");

        rbotrangthai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbotrangthai.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã Phòng");

        txtten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtten.setText("jLabel8");

        txtmaphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaphong.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Email");

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtemail.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("SDT");

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Giới Tính");

        txtgioitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtgioitinh.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Ngày Sinh");

        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaysinh.setText("jLabel17");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Địa Chỉ");

        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdiachi.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Ngày Vào Làm");

        txtngayvao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngayvao.setText("jLabel23");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Mã Chức Vụ");

        txtchucvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchucvu.setText("jLabel25");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("CCCD");

        txtcccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcccd.setText("jLabel27");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Trinh Do");

        txttrinhdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttrinhdo.setText("jLabel29");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Chuyên Nghành");

        txtchuyennghanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchuyennghanh.setText("jLabel31");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Ngày Tạo");

        txtngaytao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaytao.setText("jLabel35");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Người Tạo");

        txtnguoitao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnguoitao.setText("jLabel37");

        jLabel3.setText("Ảnh");

        lb_anh.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1067, 1067, 1067)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rbotrangthai))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaphong)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtmanv))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtten)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail)
                                            .addComponent(jLabel10))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsdt)
                                            .addComponent(jLabel12))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(txtgioitinh)))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtngaysinh)
                                            .addComponent(jLabel16)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtchucvu)
                                            .addComponent(jLabel24))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(txtcccd))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(txttrinhdo))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(txtchuyennghanh))))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(txtngaytao))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnguoitao)
                                            .addComponent(jLabel36)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(txtdiachi))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(txtngayvao))))))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(29, 29, 29)
                        .addComponent(txtngaytao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel10)))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtmanv)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtten)
                                                .addComponent(txtemail))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel16)))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtgioitinh)
                                            .addComponent(txtngaysinh)
                                            .addComponent(txtdiachi)
                                            .addComponent(txtngayvao)
                                            .addComponent(txtsdt)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(29, 29, 29)
                                .addComponent(txtnguoitao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmaphong)
                                    .addComponent(rbotrangthai, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtchucvu)
                                    .addComponent(txtcccd)
                                    .addComponent(txttrinhdo)
                                    .addComponent(txtchuyennghanh))))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    SwingUtilities.invokeLater(() -> {
        JFrame parentFrame = new JFrame(); // tạo frame cha
       String maNV = XAuth.user.getMaNV();// mã nhân viên cần lấy dữ liệu
        ThongTinCaNhan dialog = new ThongTinCaNhan(parentFrame, true);
        
        // Lấy dữ liệu nhân viên
        ThongTin thongTin = dialog.dao.findById(maNV);
        if (thongTin != null) {
            dialog.setThongTin(thongTin); // cập nhật dữ liệu lên form
        } else {
            System.out.println("Không tìm thấy nhân viên với mã: " + maNV);
        }
        
        dialog.setVisible(true);
    });

    

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel rbotrangthai;
    private javax.swing.JLabel txtcccd;
    private javax.swing.JLabel txtchucvu;
    private javax.swing.JLabel txtchuyennghanh;
    private javax.swing.JLabel txtdiachi;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtgioitinh;
    private javax.swing.JLabel txtmanv;
    private javax.swing.JLabel txtmaphong;
    private javax.swing.JLabel txtngaysinh;
    private javax.swing.JLabel txtngaytao;
    private javax.swing.JLabel txtngayvao;
    private javax.swing.JLabel txtnguoitao;
    private javax.swing.JLabel txtsdt;
    private javax.swing.JLabel txtten;
    private javax.swing.JLabel txttrinhdo;
    // End of variables declaration//GEN-END:variables

   

    public void setForm() {
    if (thongTin != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        txtmanv.setText(String.valueOf(thongTin.getMaNV()));
        txtten.setText(thongTin.getHoTen() != null ? thongTin.getHoTen() : "");
        txtemail.setText(thongTin.getEmail() != null ? thongTin.getEmail() : "");
        txtsdt.setText(thongTin.getSDT() != null ? thongTin.getSDT() : ""); // ✅ Thêm SDT tại đây
        txtgioitinh.setText(thongTin.getGioiTinh() != null ? thongTin.getGioiTinh() : "");
        txtngaysinh.setText(thongTin.getNgaySinh() != null ? sdf.format(thongTin.getNgaySinh()) : "");
        txtdiachi.setText(thongTin.getDiaChi() != null ? thongTin.getDiaChi() : "");
        txtmaphong.setText(String.valueOf(thongTin.getMaPhong()));
        txtchucvu.setText(String.valueOf(thongTin.getMaChucVu()));
        txtcccd.setText(thongTin.getCCCD() != null ? thongTin.getCCCD() : "");
        txttrinhdo.setText(thongTin.getTrinhDo() != null ? thongTin.getTrinhDo() : "");
        txtchuyennghanh.setText(thongTin.getChuyenNganh() != null ? thongTin.getChuyenNganh() : "");
        
        
        
        
          if (thongTin.getPhoto() != null && !thongTin.getPhoto().isEmpty()) {
            lb_anh.setIcon(new ImageIcon(thongTin.getPhoto()));
            lb_anh.setText(thongTin.getPhoto());
        } else {
            lb_anh.setIcon(null);
            lb_anh.setText("Chưa chọn ảnh");
        }
   
        txtngaytao.setText(thongTin.getNgayTao() != null ? sdf.format(thongTin.getNgayTao()) : "");
        txtnguoitao.setText(thongTin.getNguoiTao() != null ? thongTin.getNguoiTao() : "");
        txtngayvao.setText(thongTin.getNgayVao() != null ? sdf.format(thongTin.getNgayVao()) : "");
        rbotrangthai.setText(thongTin.getTrangThai() != null ? thongTin.getTrangThai() : "");
        
        
    } else {
        txtmanv.setText("");
        txtten.setText("");
        txtemail.setText("");
        txtsdt.setText(""); // ✅ Đặt trống SDT nếu null
        txtgioitinh.setText("");
        txtngaysinh.setText("");
        txtdiachi.setText("");
        txtmaphong.setText("");
        txtchucvu.setText("");
        txtcccd.setText("");
        txttrinhdo.setText("");
        txtchuyennghanh.setText("");
       
        txtngaytao.setText("");
        txtnguoitao.setText("");
        txtngayvao.setText("");
        rbotrangthai.setText("");
    }
}


    // Phương thức set dữ liệu ThongTin vào biến thành viên, và cập nhật form
    public void setThongTin(ThongTin thongTin) {
        this.thongTin = thongTin;
        setForm();
    }
   

}
