/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.manager;

import duan1.DAO.ipml.dangkitangcaimpl;
import duan1.controller.dangkitangcacontroller;
import duan1.entity.dangkitangca;
import duan1.util.XAuth;
import duan1.util.XDialog;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author hang
 */
public class dangkitangca1manager extends javax.swing.JDialog implements dangkitangcacontroller {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dangkitangca1manager.class.getName());
    private dangkitangcaimpl dao = new dangkitangcaimpl();
    private dangkitangcaManager parentForm; // Thêm biến để lưu reference đến form cha
    private Timer timer;
    private boolean addMode = false;

    /**
     * Creates new form dangkitangca1manager
     */
    public dangkitangca1manager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        setLocationRelativeTo(parent);
    }

    public void init() {
        showTime();
        refreshUiStateBasedOnApproval();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        cbx_Loaitangca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkin = new javax.swing.JButton();
        checkout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_matangca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbx_Loaitangca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày Thường", "Thứ 7, CN", "Ngày Lễ" }));

        jLabel4.setText("Loại Tăng ca");

        checkin.setText("checkin");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });

        checkout1.setText("checkout");
        checkout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Tăng Ca");

        lblTime.setText("Thời Gian");

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane1.setViewportView(txt_ghichu);

        jLabel2.setText("Lý do");

        jLabel3.setText("Mã tăng ca ");

        jButton1.setText("Xoá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_matangca.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(checkin)
                        .addGap(96, 96, 96)
                        .addComponent(checkout1)
                        .addGap(92, 92, 92)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(423, 423, 423)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_matangca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbx_Loaitangca, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_Loaitangca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txt_matangca)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkin)
                    .addComponent(checkout1)
                    .addComponent(jButton1))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        this.checkin();
    }//GEN-LAST:event_checkinActionPerformed

    private void checkout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout1ActionPerformed
        this.checkout();
    }//GEN-LAST:event_checkout1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.xoa();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dangkitangca1manager dialog = new dangkitangca1manager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_Loaitangca;
    private javax.swing.JButton checkin;
    private javax.swing.JButton checkout1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JLabel txt_matangca;
    // End of variables declaration//GEN-END:variables

    private void showTime() {
        timer = new Timer(1000, e -> {
            lblTime.setText("Bây giờ: " + new java.sql.Time(System.currentTimeMillis()));
        });
        timer.start();
    }

    private void refreshUiStateBasedOnApproval() {
        try {
            // Nếu đang ở chế độ thêm mới
            if (addMode) {
                configureUiForAddMode();
                return;
            }

            duan1.entity.dangkitangca record = null;

            // Ưu tiên tìm theo mã trên form
            String rawId = txt_matangca.getText();
            if (rawId != null && !rawId.trim().isEmpty()) {
                record = dao.findById(rawId.trim()); // Không tách số
            }

            // Nếu không tìm thấy => tìm bản ghi hôm nay của nhân viên hiện tại
            if (record == null) {
                String maNV = XAuth.user.getMaNV();
                String ngayHienTai = java.time.LocalDate.now().toString();
                record = dao.findAnyOvertimeRecord(maNV, ngayHienTai);
            }

            // Nếu vẫn không có => chỉ cho checkin
            if (record == null) {
                configureUiOnlyCheckin();
                return;
            }

            // Kiểm tra trạng thái duyệt
            boolean daDuyet = "Đã duyệt".equalsIgnoreCase(record.getTrangThai());

            if (daDuyet) {
                configureUiOnlyCheckout();
            } else {
                configureUiOnlyDelete();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void configureUiOnlyCheckin() {
        checkin.setVisible(true);
        checkin.setEnabled(true);

        checkout1.setVisible(false);
        checkout1.setEnabled(false);

        jButton1.setVisible(false);
        jButton1.setEnabled(false);
    }

    private void configureUiOnlyDelete() {
        checkin.setVisible(false);
        checkin.setEnabled(false);

        checkout1.setVisible(false);
        checkout1.setEnabled(false);

        jButton1.setVisible(true);
        jButton1.setEnabled(true);
    }

    private void configureUiOnlyCheckout() {
        checkin.setVisible(false);
        checkin.setEnabled(false);

        checkout1.setVisible(true);
        checkout1.setEnabled(true);

        jButton1.setVisible(false);
        jButton1.setEnabled(false);
    }

    private void configureUiForAddMode() {
        configureUiOnlyCheckin();
    }

    private void configureUiForEntity(dangkitangca entity) {
        if (entity == null) {
            configureUiOnlyCheckin();
            return;
        }
        String trangThai = entity.getTrangThai();
        boolean daDuyet = trangThai != null && trangThai.equalsIgnoreCase("Đã duyệt");
        if (daDuyet) {
            configureUiOnlyCheckout();
        } else {
            configureUiOnlyDelete();
        }
    }

    public void openForAddMode() {
        this.addMode = true;
        configureUiForAddMode();
    }

    public dangkitangca getform() {
        dangkitangca a = new dangkitangca();
        String manv = XAuth.user.getMaNV();
        a.setMaNV(manv);
        String loaiTangCa = cbx_Loaitangca.getSelectedItem().toString(); // Lấy loại
        double heSo = 0;
        String loaiTangCaDB = "";
        switch (loaiTangCa) {
            case "Ngày Thường":
                heSo = 1.5;
                loaiTangCaDB = "NgayThuong";
                break;
            case "Thứ 7, CN":
                heSo = 2.0;
                loaiTangCaDB = "T7_CN";
                break;
            case "Ngày Lễ":
                heSo = 3.0;
                loaiTangCaDB = "Le";
                break;
            default:

                break;
        }

// Bây giờ bạn có:
        a.setHeSo(heSo);
        a.setLoaiTangCa(loaiTangCaDB);

        String ngay = LocalDate.now().toString(); // "2025-07-30"
        Date sqlDate = Date.valueOf(ngay);
        a.setNgay(String.valueOf(sqlDate));

        LocalTime gio = LocalTime.now();
        String gioDinhDang = gio.toString().substring(0, 8); // "23:10:20"
        a.setCheckin(gioDinhDang);

        a.setGhiChu(txt_ghichu.getText());
        String ten = XAuth.user.getFullname();
        a.setNguoiTao(ten);
        return a;
    }

    @Override
    public void them() {

    }

    @Override
    public void sua() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void xoa() {
        try {
            String rawId = txt_matangca.getText();
            String idToDelete = null;

            if (rawId != null && !rawId.trim().isEmpty()) {
                idToDelete = rawId.trim();
            }

            if (idToDelete == null) {
                // Lấy bản ghi hôm nay của NV hiện tại
                String maNV = XAuth.user.getMaNV();
                String ngayHienTai = java.time.LocalDate.now().toString();
                dangkitangca record = dao.findAnyOvertimeRecord(maNV, ngayHienTai);
                if (record == null) {
                    XDialog.alert("❌ Không có đăng ký tăng ca để xoá!");
                    return;
                }
                if ("Đã duyệt".equalsIgnoreCase(record.getTrangThai())) {
                    XDialog.alert("❌ Ca đã được duyệt, không thể xoá!");
                    return;
                }
                if (record.getMaTangCa() == null || record.getMaTangCa().trim().isEmpty()) {
                    XDialog.alert("❌ Mã tăng ca không hợp lệ!");
                    return;
                }
                idToDelete = record.getMaTangCa().trim();
            }

            dao.deleteById(idToDelete);
            XDialog.alert("✅ Xoá đăng ký tăng ca thành công");
            txt_matangca.setText("");
            refreshUiStateBasedOnApproval();
        } catch (Exception ex) {
            ex.printStackTrace();
            XDialog.alert("❌ Lỗi khi xoá đăng ký tăng ca!");
        }
    }

    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkin() {
        try {
            // Kiểm tra xem đã checkin hôm nay chưa
            String maNV = XAuth.user.getMaNV();
            String ngayHienTai = LocalDate.now().toString();
            dangkitangca existingRecord = dao.findAnyOvertimeRecord(maNV, ngayHienTai);

            if (existingRecord != null) {
                XDialog.alert("❌ Bạn đã có ca tăng ca hôm nay rồi!");
                return;
            }

            dangkitangca entity = getform();
            if (entity == null) {
                return;
            }

            dao.create(entity);
            XDialog.alert("✅ Checkin tăng ca thành công!");
            refreshUiStateBasedOnApproval();

        } catch (Exception ex) {
            ex.printStackTrace();
            XDialog.alert("❌ Lỗi khi checkin tăng ca!");
        }
    }

    @Override
    public void checkout() {
        try {
            String maNV = XAuth.user.getMaNV();
            LocalTime gio = LocalTime.now();
            String gioDinhDang = gio.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            String ngayHienTai = LocalDate.now().toString();

            // Chặn: nếu hôm nay đã có bản ghi và đã checkout rồi, không cho checkout nữa
            dangkitangca anyToday = dao.findAnyOvertimeRecord(maNV, ngayHienTai);
            if (anyToday != null && anyToday.getCheckout() != null && !anyToday.getCheckout().trim().isEmpty()) {
                XDialog.alert("❌ Bạn đã check out tăng ca hôm nay rồi!");
                return;
            }

            // Ưu tiên dùng mã tăng ca trên form nếu có (khi mở từ bảng)
            String rawId = txt_matangca.getText();
            if (rawId != null && !rawId.trim().isEmpty()) {
                dao.updateCheckout(rawId.trim(), gioDinhDang);
                XDialog.alert("✅ Check out tăng ca thành công!");
                refreshUiStateBasedOnApproval();
                return;
            }

            // Nếu không có mã trên form, tìm record tăng ca hiện tại của nhân viên theo ngày hôm nay
            dangkitangca currentRecord = dao.findCurrentOvertimeRecord(maNV, ngayHienTai);
            if (currentRecord == null) {
                XDialog.alert("❌ Không tìm thấy ca tăng ca nào để check out!");
                return;
            }

            // Cập nhật checkout với mã tăng ca thực tế
            dao.updateCheckout(currentRecord.getMaTangCa(), gioDinhDang);

            XDialog.alert("✅ Check out tăng ca thành công!");
            refreshUiStateBasedOnApproval();
        } catch (Exception ex) {
            ex.printStackTrace();
            XDialog.alert("❌ Lỗi khi check out!");
        }
    }

    public void setForm(dangkitangca entity) {
        if (entity != null) {
            // Set các giá trị vào form để chỉnh sửa
            cbx_Loaitangca.setSelectedItem(entity.getLoaiTangCa());
            txt_ghichu.setText(entity.getGhiChu());
            txt_matangca.setText(String.valueOf(entity.getMaTangCa()));
            // Có thể thêm các field khác nếu cần
            this.addMode = false;
            configureUiForEntity(entity);
        }
    }

}
