/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.manager;

import duan1.DAO.ipml.quanlychamcongimpl;
import duan1.entity.Luong;
import duan1.entity.chamcong;
import duan1.util.XAuth;
import duan1.util.XDialog;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hang
 */
public class xemchamcongnhanvienmanager extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(xemchamcongnhanvienmanager.class.getName());
    quanlychamcongimpl dao = new quanlychamcongimpl();
    /**
     * Creates new form xemchamcongnhanvienmanager
     */
    public xemchamcongnhanvienmanager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init(){
    filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        txt_thang = new javax.swing.JTextField();
        txt_nam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã chấm công", "Mã nhân viên", "Ngày", "Checkin", "Checkout", "đi làm", "đi muộn", "về sớm", "tổng giờ", "ghi chú"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Năm");

        jLabel2.setText("Tháng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timkiemChamCong();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                xemchamcongnhanvienmanager dialog = new xemchamcongnhanvienmanager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txt_nam;
    private javax.swing.JTextField txt_thang;
    // End of variables declaration//GEN-END:variables


public void filltable() {
    String manv = XAuth.user.getMaNV(); // hoặc lấy từ form, ví dụ: Integer.parseInt(txt_manv.getText())
    
    List<chamcong> list = dao.findall2(manv);

    DefaultTableModel model = (DefaultTableModel) tb1.getModel();
    model.setRowCount(0); // xóa dữ liệu cũ

    for (chamcong n : list) {
        model.addRow(new Object[]{
            n.getMaChamCong(),
            n.getMaNV(),
            n.getNgay(),
            n.getCheckIn(),
            n.getCheckOut(),
            n.isDiLam() ? "Có" : "Không",
            n.isDiMuon() ? "Không" : "Có",
            n.isVeSom() ? "Không" : "Có",
            n.getTongGio(),
            n.getGhiChu()
        });
    }
} 

public void timkiemChamCong() {
    try {
        String manv = XAuth.user.getMaNV();
        int thang = Integer.parseInt(txt_thang.getText().trim());
        int nam = Integer.parseInt(txt_nam.getText().trim());

        List<chamcong> list = dao.searchChamCong(manv, thang, nam); // sửa lại tên hàm dao đúng mục đích

        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);

        for (chamcong n : list) {
            model.addRow(new Object[]{
                n.getMaChamCong(),
                n.getMaNV(),
                n.getNgay(),
                n.getCheckIn(),
                n.getCheckOut(),
                n.isDiLam() ? "Có" : "Không",
                n.isDiMuon() ? "Có" : "Không",
                n.isVeSom() ? "Có" : "Không",
                n.getTongGio(),
                n.getGhiChu()
            });
        }

        if (list.isEmpty()) {
            XDialog.alert("Không tìm thấy dữ liệu chấm công cho tháng/năm đã nhập.");
        }

    } catch (NumberFormatException e) {
        XDialog.alert("Vui lòng nhập đúng định dạng số cho Tháng và Năm.");
        filltable(); // load lại dữ liệu gốc
    } catch (Exception e) {
        e.printStackTrace();
        XDialog.alert("Lỗi khi tìm kiếm: " + e.getMessage());
    }
}






}
