/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1.manager;

import duan1.DAO.ipml.TTCaNhanDAOimpl;
import duan1.entity.ThongTin;
import duan1.util.XAuth;
import duan1.util.XDialog;
import duan1.util.XIcon;
import javax.swing.ImageIcon;

/**
 *
 * @author hang
 */
public class xemthongtincanhan extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(xemthongtincanhan.class.getName());

    /**
     * Creates new form xemthongtincanhan
     */
    public xemthongtincanhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    
    public void init(){
    setfrom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnguoitao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_anh = new javax.swing.JLabel();
        txtgioitinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtchucvu = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JLabel();
        rbotrangthai = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttrinhdo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtten = new javax.swing.JLabel();
        txtchuyennghanh = new javax.swing.JLabel();
        txtmaphong = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Cá Nhân");

        txtnguoitao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnguoitao.setText("jLabel37");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Ảnh");

        txtmanv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmanv.setText("jLabel3");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Giới Tính");

        lb_anh.setText("jLabel5");

        txtgioitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtgioitinh.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Ngày Sinh");

        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaysinh.setText("jLabel17");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Địa Chỉ");

        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdiachi.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Ngày Vào Làm");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Mã Chức Vụ");

        txtchucvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchucvu.setText("jLabel25");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("CCCD");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Trạng Thái");

        txtcccd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcccd.setText("jLabel27");

        rbotrangthai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbotrangthai.setText("jLabel5");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Trinh Do");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên");

        txttrinhdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttrinhdo.setText("jLabel29");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã Phòng");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Chuyên Nghành");

        txtten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtten.setText("jLabel8");

        txtchuyennghanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtchuyennghanh.setText("jLabel31");

        txtmaphong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaphong.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Email");

        txtngaytao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngaytao.setText("jLabel35");

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtemail.setText("jLabel11");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Người Tạo");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("SDT");

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtmanv)
                    .addComponent(jLabel4)
                    .addComponent(rbotrangthai))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaphong)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtten)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(142, 142, 142)))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemail)
                    .addComponent(jLabel10)
                    .addComponent(txtchucvu)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsdt)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(txtcccd))))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtgioitinh))))
                    .addComponent(jLabel28)
                    .addComponent(txttrinhdo))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngaysinh)
                            .addComponent(jLabel16)))
                    .addComponent(jLabel30)
                    .addComponent(txtchuyennghanh))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtdiachi))
                        .addGap(15, 15, 15))
                    .addComponent(txtnguoitao)
                    .addComponent(jLabel36))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtngaytao))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(txtmanv)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(rbotrangthai))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(txtten)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(txtmaphong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addComponent(txtemail)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel24)
                                .addGap(29, 29, 29)
                                .addComponent(txtchucvu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(35, 35, 35)
                                .addComponent(txtsdt)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel26)
                                .addGap(29, 29, 29)
                                .addComponent(txtcccd)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtgioitinh)
                                .addComponent(txtngaytao))
                            .addGap(98, 98, 98)
                            .addComponent(jLabel28)
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttrinhdo)
                                .addComponent(txtchuyennghanh))
                            .addGap(8, 8, 8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel16))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtngaysinh)
                            .addComponent(txtdiachi))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel30)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel36)
                                .addGap(29, 29, 29)
                                .addComponent(txtnguoitao)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                xemthongtincanhan dialog = new xemthongtincanhan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel rbotrangthai;
    private javax.swing.JLabel txtcccd;
    private javax.swing.JLabel txtchucvu;
    private javax.swing.JLabel txtchuyennghanh;
    private javax.swing.JLabel txtdiachi;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtgioitinh;
    private javax.swing.JLabel txtmanv;
    private javax.swing.JLabel txtmaphong;
    private javax.swing.JLabel txtngaysinh;
    private javax.swing.JLabel txtngaytao;
    private javax.swing.JLabel txtnguoitao;
    private javax.swing.JLabel txtsdt;
    private javax.swing.JLabel txtten;
    private javax.swing.JLabel txttrinhdo;
    // End of variables declaration//GEN-END:variables

    public void setfrom() {
        TTCaNhanDAOimpl a = new TTCaNhanDAOimpl();
        String Manv = XAuth.user.getMaNV();
        ThongTin tt = a.findById(Manv);
      
        if (tt != null) {
            System.out.println("Tìm thấy nhân viên: " + tt.getHoTen());
            System.out.println("Đường dẫn ảnh: " + tt.getPhoto());
        } else {
            System.out.println("Không tìm thấy nhân viên.");
        }


        if (tt != null) {
            txtmanv.setText(String.valueOf(tt.getMaNV()));
            txtten.setText(ensureNotNull(tt.getHoTen()));
            txtemail.setText(ensureNotNull(tt.getEmail()));
            txtsdt.setText(ensureNotNull(tt.getSDT()));
            txtgioitinh.setText(ensureNotNull(tt.getGioiTinh()));
            txtngaysinh.setText(tt.getNgaySinh() != null ? tt.getNgaySinh().toString() : "");
            txtdiachi.setText(ensureNotNull(tt.getDiaChi()));
            txtmaphong.setText(String.valueOf(tt.getMaPhong()));
            txtchucvu.setText(String.valueOf(tt.getMaChucVu()));
            txtcccd.setText(ensureNotNull(tt.getCCCD()));
            txttrinhdo.setText(ensureNotNull(tt.getTrinhDo()));
            txtchuyennghanh.setText(ensureNotNull(tt.getChuyenNganh()));
            txtngaytao.setText(tt.getNgayTao() != null ? tt.getNgayTao().toString() : "");
            txtnguoitao.setText(ensureNotNull(tt.getNguoiTao()));
           
            rbotrangthai.setText(ensureNotNull(tt.getTrangThai()));

            // Nếu có ảnh, load vào JLabel
             if (tt.getPhoto() != null && !tt.getPhoto().isEmpty()) {
                 try {
                     System.out.println("Đang load ảnh từ: " + tt.getPhoto());
                     // Sử dụng XIcon utility để load và resize ảnh
                     XIcon.setIcon(lb_anh, tt.getPhoto());
                     lb_anh.setText(""); // Xóa text để chỉ hiển thị ảnh
                     System.out.println("Load ảnh thành công!");
                 } catch (Exception e) {
                     System.out.println("Lỗi load ảnh: " + e.getMessage());
                     lb_anh.setText("Không thể hiển thị ảnh");
                 }
             } else {
                 lb_anh.setText("Chưa có ảnh");
             }
        } else {
            XDialog.alert(null, "Không tìm thấy nhân viên.");
        }
    }

    private String ensureNotNull(String value) {
        return value == null ? "" : value;
    }

}
